# Copyright (c) 2026, one-fm and contributors
# For license information, please see license.txt
"""
Seed the four Google connectors into a fresh site.

Connectors are DocType rows, so a new site starts with an empty modeler until
something creates them. That used to be a directory of JSON manifests read at
runtime — which meant every connector existed twice, once as a file and once as
a row, and the two drifted apart the moment anyone edited a row. The files are
gone. This is the only definition, and it is applied once.

WHAT THIS IS
------------
A snapshot of a working installation, in the same portable shape that
``Export JSON`` produces on the connector form: four connectors, 25 operations,
their fields, and — for the 16 operations that are plain REST — the URL, query,
body and response mapping that let them run with no Python at all.

It is DATA, not behaviour, and it goes in through the ordinary import path
(``connectors.seed.import_manifest``) rather than a second bespoke writer. What
ships is therefore exactly what an export produces, which is what keeps the
snapshot honest.

IT DOES NOT OVERWRITE
---------------------
A connector that already exists is left exactly as it is. Sites set their own
base URLs, credentials, scopes and allowed roles, and a patch that re-applied on
every migrate would quietly undo that. Only what is missing is created.

Credentials are never seeded — a key belongs to the site, not the codebase.
"""

import frappe

# Generated from a working installation, so what ships is what was tested rather
# than what someone typed a second time.
GOOGLE_CONNECTORS = \
[{'connectorId': 'google_drive',
  'label': 'Google Drive',
  'description': 'Read, create, update, share and list files in Google Drive.',
  'icon': {'path': 'M7.71 3.5 1.15 15l3.42 6 6.57-11.5zM9.73 15l-3.42 6h13.54l3.42-6zM22.85 15 '
                   '16.28 3.5H9.44l6.57 11.5z',
           'color': '#4285f4',
           'label': 'Google Drive'},
  'api': {'name': 'drive',
          'version': 'v3',
          'discovery': 'https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'},
  'execution': {'type': 'HTTP Request',
                'baseUrl': 'https://www.googleapis.com/drive/v3',
                'timeout': 30,
                'auth': {'type': 'Service Account JSON',
                         'source': 'On this connector',
                         'headerName': 'X-API-Key',
                         'scopes': 'https://www.googleapis.com/auth/drive'}},
  'operations': [{'value': 'copyFile',
                  'label': 'Copy file (instantiate a template)',
                  'method': 'files.copy',
                  'description': 'Duplicates a document, keeping its design exactly — logos, '
                                 'tables, named styles, bilingual layout and RTL runs all '
                                 'survive. Use this to instantiate a branded template, then '
                                 'fill it with Google Docs → Fill template. Do NOT follow it '
                                 'with Update file content: that replaces the whole body and '
                                 'destroys the template.',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'files/{{ params.file }}/copy',
                           'query': {'supportsAllDrives': 'true',
                                     'fields': 'id,name,webViewLink'},
                           'contentType': 'application/json',
                           'body': '{%- set b = {} -%}{%- if params.filename %}{% set _ = '
                                   "b.update({'name': params.filename}) %}{% endif -%}{%- if "
                                   "params.folder %}{% set _ = b.update({'parents': "
                                   '[params.folder]}) %}{% endif -%}{{ b | tojson }}',
                           'responseMap': {'id': 'id',
                                           'name': 'name',
                                           'webViewLink': 'webViewLink'}},
                  'fields': [{'name': 'file',
                              'label': 'Template',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id',
                              'help': 'The template to copy — paste its link or id. The '
                                      'service account needs at least Viewer on it.'},
                             {'name': 'filename',
                              'label': 'New file name',
                              'type': 'String',
                              'help': 'Leave blank and Drive names it “Copy of …” — pass the '
                                      'real document title instead.'},
                             {'name': 'folder',
                              'label': 'Destination folder',
                              'type': 'String',
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id',
                              'help': 'Where the copy goes. Omit it and the copy lands beside '
                                      'the template, which is almost never wanted.'}],
                  'output': {'id': 'File id',
                             'name': 'File name',
                             'webViewLink': 'Open-in-Drive URL'}},
                 {'value': 'downloadText',
                  'label': 'Download text',
                  'method': 'files.export / files.get(media)',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_drive_ops.download_text',
                  'fields': [{'name': 'file',
                              'label': 'File',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id',
                              'help': 'The file to read. Paste a Drive link or a file id.'}],
                  'output': {'text': 'Plain-text content of the file'}},
                 {'value': 'createFile',
                  'label': 'Create file',
                  'method': 'files.create',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_drive_ops.create_file',
                  'fields': [{'name': 'folder',
                              'label': 'Folder',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id',
                              'help': 'Destination Drive folder — paste a folder link or id. '
                                      'The service account must have write access.'},
                             {'name': 'filename',
                              'label': 'File name',
                              'type': 'String',
                              'required': True},
                             {'name': 'content', 'label': 'Content', 'type': 'Text'},
                             {'name': 'targetMimeType',
                              'label': 'Create as',
                              'type': 'Dropdown',
                              'default': 'application/vnd.google-apps.document',
                              'choices': [{'label': 'Google Doc',
                                           'value': 'application/vnd.google-apps.document'},
                                          {'label': 'Google Slides',
                                           'value': 'application/vnd.google-apps.presentation'},
                                          {'label': 'Google Sheet',
                                           'value': 'application/vnd.google-apps.spreadsheet'},
                                          {'label': 'Keep source format', 'value': ''}]},
                             {'name': 'sourceMimeType',
                              'label': 'Source format',
                              'type': 'String',
                              'default': 'text/markdown'}],
                  'output': {'id': 'File id',
                             'name': 'File name',
                             'webViewLink': 'Open-in-Drive URL'}},
                 {'value': 'updateFileContent',
                  'label': 'Update file content',
                  'method': 'files.update',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_drive_ops.update_file_content',
                  'fields': [{'name': 'file',
                              'label': 'File',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'content', 'label': 'Content', 'type': 'Text'},
                             {'name': 'sourceMimeType',
                              'label': 'Source format',
                              'type': 'String',
                              'default': 'text/markdown'}],
                  'output': {'id': 'File id',
                             'name': 'File name',
                             'webViewLink': 'Open-in-Drive URL'}},
                 {'value': 'setPermissions',
                  'label': 'Share file',
                  'method': 'permissions.create',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_drive_ops.set_permissions',
                  'fields': [{'name': 'file',
                              'label': 'File',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'type',
                              'label': 'Grantee type',
                              'type': 'Dropdown',
                              'required': True,
                              'choices': [{'label': 'User', 'value': 'user'},
                                          {'label': 'Group', 'value': 'group'},
                                          {'label': 'Domain', 'value': 'domain'},
                                          {'label': 'Anyone', 'value': 'anyone'}]},
                             {'name': 'role',
                              'label': 'Role',
                              'type': 'Dropdown',
                              'required': True,
                              'default': 'reader',
                              'choices': [{'label': 'Reader', 'value': 'reader'},
                                          {'label': 'Commenter', 'value': 'commenter'},
                                          {'label': 'Writer', 'value': 'writer'},
                                          {'label': 'File organizer', 'value': 'fileOrganizer'},
                                          {'label': 'Organizer', 'value': 'organizer'},
                                          {'label': 'Owner', 'value': 'owner'}]},
                             {'name': 'emailAddress',
                              'label': 'Email',
                              'type': 'String',
                              'condition': {'field': 'type', 'oneOf': ['user', 'group']}},
                             {'name': 'domain',
                              'label': 'Domain',
                              'type': 'String',
                              'condition': {'field': 'type', 'equals': 'domain'}},
                             {'name': 'grants',
                              'label': 'Grants (advanced JSON)',
                              'type': 'Text',
                              'help': 'Optional: a JSON array of Permission resources. '
                                      'Overrides the single grant above.'}],
                  'output': {'granted': 'Number of permissions applied'}},
                 {'value': 'listFiles',
                  'label': 'List files',
                  'method': 'files.list',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'GET',
                           'url': 'files',
                           'query': {'supportsAllDrives': 'true',
                                     'includeItemsFromAllDrives': 'true',
                                     'q': "'{{ params.folder }}' in parents and trashed = "
                                          'false',
                                     'fields': 'files(id,name,mimeType,modifiedTime)',
                                     'pageSize': '{{ params.pageSize or 20 }}'},
                           'contentType': 'application/json',
                           'responseMap': {'files': 'files'}},
                  'fields': [{'name': 'folder',
                              'label': 'Folder',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'pageSize',
                              'label': 'Max results',
                              'type': 'String',
                              'default': '20'}],
                  'output': {'files': 'Array of {id,name,mimeType,modifiedTime}',
                             'count': 'Number of files'}},
                 {'value': 'revokePermissions',
                  'label': 'Revoke sharing',
                  'method': 'permissions.list + permissions.delete',
                  'description': 'Withdraw access without touching the file. The counterpart '
                                 'to Share file — use it to take a document out of circulation '
                                 'while keeping it and its history intact.',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_drive_ops.revoke_permissions',
                  'fields': [{'name': 'file',
                              'label': 'File',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'scope',
                              'label': 'Revoke',
                              'type': 'Dropdown',
                              'required': True,
                              'default': 'all',
                              'choices': [{'label': 'All sharing (keep owner)', 'value': 'all'},
                                          {'label': 'Domain grants only', 'value': 'domain'},
                                          {'label': 'User grants only', 'value': 'user'}]},
                             {'name': 'match',
                              'label': 'Only this domain / email',
                              'type': 'String',
                              'condition': {'field': 'scope', 'oneOf': ['domain', 'user']},
                              'help': 'Optional. Leave blank to revoke every grant of the '
                                      'chosen kind. The owner is never removed.'}],
                  'output': {'revoked': 'Number of grants removed',
                             'skipped': 'Number that could not be removed (structural or '
                                        'inherited from a parent folder)',
                             'grants': 'The grants that were removed',
                             'skipped_grants': 'The grants that were left, each with a reason',
                             'file': 'File id'}},
                 {'value': 'deleteFile',
                  'label': 'Delete file',
                  'method': 'files.delete / files.update(trashed)',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'PATCH',
                           'url': 'files/{{ params.file }}',
                           'query': {'supportsAllDrives': 'true', 'fields': 'id'},
                           'contentType': 'application/json',
                           'body': '{"trashed": true}',
                           'responseMap': {'id': 'id'}},
                  'fields': [{'name': 'file',
                              'label': 'File',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'}],
                  'output': {'deleted': 'File id', 'permanent': 'Whether it bypassed trash'}}]},
 {'connectorId': 'google_docs',
  'label': 'Google Docs',
  'description': 'Create and edit Google Docs — insert/replace/append text, read content.',
  'icon': {'path': 'M6 2h8l6 6v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2m7 1.5V9h5.5zM8 '
                   '9h4v1.5H8zm0 4h8v1.5H8zm0 4h8v1.5H8z',
           'color': '#1a73e8',
           'label': 'Google Docs'},
  'api': {'name': 'docs',
          'version': 'v1',
          'discovery': 'https://docs.googleapis.com/$discovery/rest?version=v1'},
  'execution': {'type': 'HTTP Request',
                'baseUrl': 'https://docs.googleapis.com/v1',
                'timeout': 30,
                'auth': {'type': 'Service Account JSON',
                         'source': 'On this connector',
                         'headerName': 'X-API-Key',
                         'scopes': 'https://www.googleapis.com/auth/documents\n'
                                   'https://www.googleapis.com/auth/drive'}},
  'operations': [{'value': 'createDocument',
                  'label': 'Create document',
                  'method': 'files.create (Drive) — see google_docs.create_document',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'https://www.googleapis.com/drive/v3/files',
                           'query': {'supportsAllDrives': 'true',
                                     'fields': 'id,name,webViewLink'},
                           'contentType': 'application/json',
                           'body': "{%- set b = {'name': params.title, 'mimeType': "
                                   "'application/vnd.google-apps.document'} -%}{%- if "
                                   "params.folder %}{% set _ = b.update({'parents': "
                                   '[params.folder]}) %}{% endif -%}{{ b | tojson }}',
                           'responseMap': {'documentId': 'id',
                                           'title': 'name',
                                           'webViewLink': 'webViewLink'}},
                  'fields': [{'name': 'folder',
                              'label': 'Folder',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id',
                              'help': 'Destination Drive folder — paste a folder link or id. '
                                      'Must be a Shared Drive folder the service account can '
                                      'write to: a service account has no My Drive quota of '
                                      'its own.'},
                             {'name': 'title',
                              'label': 'Title',
                              'type': 'String',
                              'required': True}],
                  'output': {'documentId': 'New document id',
                             'title': 'Title',
                             'url': 'Open-in-Drive URL'}},
                 {'value': 'insertText',
                  'label': 'Insert text',
                  'method': 'documents.batchUpdate → insertText',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'documents/{{ params.document }}:batchUpdate',
                           'contentType': 'application/json',
                           'body': "{{ {'requests': [{'insertText': {'location': {'index': "
                                   "(params.index or 1) | int}, 'text': params.text or ''}}]} "
                                   '| tojson }}',
                           'responseMap': {'documentId': 'documentId'}},
                  'fields': [{'name': 'document',
                              'label': 'Document',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'text',
                              'label': 'Text',
                              'type': 'Text',
                              'required': True},
                             {'name': 'index',
                              'label': 'At index',
                              'type': 'String',
                              'default': '1',
                              'help': '1-based structural index. 1 = start of body.'}],
                  'output': {'documentId': 'Document id'}},
                 {'value': 'appendText',
                  'label': 'Append text',
                  'method': 'documents.batchUpdate → insertText (at end)',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_docs_ops.append_text',
                  'fields': [{'name': 'document',
                              'label': 'Document',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'text',
                              'label': 'Text',
                              'type': 'Text',
                              'required': True}],
                  'output': {'documentId': 'Document id'}},
                 {'value': 'fillTemplate',
                  'label': 'Fill template',
                  'method': 'documents.batchUpdate',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_docs_ops.fill_template',
                  'fields': [{'name': 'document',
                              'label': 'Document',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id',
                              'help': 'The copied template to fill.'},
                             {'name': 'values',
                              'label': 'Placeholder values',
                              'type': 'Text',
                              'required': True,
                              'help': 'JSON object of placeholder → replacement, e.g. '
                                      '{"{{title}}": "Leave Policy", "{{owner}}": "HR"}.'},
                             {'name': 'matchCase',
                              'label': 'Match case',
                              'type': 'Boolean',
                              'default': 'true'},
                             {'name': 'failIfUnfilled',
                              'label': 'Fail if a placeholder is not found',
                              'type': 'Boolean',
                              'default': 'true',
                              'help': 'A placeholder split across formatting runs will not '
                                      'match. Leaving this on stops a document going out with '
                                      '“{{owner}}” still printed in it.'}],
                  'output': {'filled': 'Per-placeholder substitution counts',
                             'unfilled': 'Placeholders that matched nothing',
                             'total': 'Total substitutions made'}},
                 {'value': 'replaceAllText',
                  'label': 'Replace all text (template fill)',
                  'method': 'documents.batchUpdate → replaceAllText',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'documents/{{ params.document }}:batchUpdate',
                           'contentType': 'application/json',
                           'body': '{"requests": [{"replaceAllText": {"containsText": {"text": '
                                   '{{ params.find | tojson }}, "matchCase": {{ \'true\' if '
                                   '(params.matchCase | string | lower) in '
                                   "['1','true','yes','on'] else 'false' "
                                   '}}},"replaceText": {{ (params.replace or "") | tojson '
                                   '}}}}]}',
                           'responseMap': {'documentId': 'documentId',
                                           'occurrencesChanged': 'replies[0].replaceAllText.occurrencesChanged'}},
                  'fields': [{'name': 'document',
                              'label': 'Document',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'find',
                              'label': 'Find text',
                              'type': 'String',
                              'required': True},
                             {'name': 'replace', 'label': 'Replace with', 'type': 'Text'},
                             {'name': 'matchCase', 'label': 'Match case', 'type': 'Boolean'}],
                  'output': {'documentId': 'Document id',
                             'occurrencesChanged': 'Number of replacements'}},
                 {'value': 'getText',
                  'label': 'Get text',
                  'method': 'documents.get + walk',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_docs_ops.get_text',
                  'fields': [{'name': 'document',
                              'label': 'Document',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'}],
                  'output': {'text': 'Plain text of the document body'}}]},
 {'connectorId': 'google_sheets',
  'label': 'Google Sheets',
  'description': 'Create spreadsheets and read/write/append/clear cell ranges.',
  'icon': {'path': 'M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1m1 '
                   '2v3h5V5zm7 0v3h5V5zM5 10v3h5v-3zm7 0v3h5v-3zM5 15v4h5v-4zm7 0v4h5v-4z',
           'color': '#34a853',
           'label': 'Google Sheets'},
  'api': {'name': 'sheets',
          'version': 'v4',
          'discovery': 'https://sheets.googleapis.com/$discovery/rest?version=v4'},
  'execution': {'type': 'HTTP Request',
                'baseUrl': 'https://sheets.googleapis.com/v4',
                'timeout': 30,
                'auth': {'type': 'Service Account JSON',
                         'source': 'On this connector',
                         'headerName': 'X-API-Key',
                         'scopes': 'https://www.googleapis.com/auth/spreadsheets\n'
                                   'https://www.googleapis.com/auth/drive'}},
  'operations': [{'value': 'createSpreadsheet',
                  'label': 'Create spreadsheet',
                  'method': 'drive.files.create (spreadsheet mimeType)',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'https://www.googleapis.com/drive/v3/files',
                           'query': {'supportsAllDrives': 'true',
                                     'fields': 'id,name,webViewLink'},
                           'contentType': 'application/json',
                           'body': "{%- set b = {'name': params.title, 'mimeType': "
                                   "'application/vnd.google-apps.spreadsheet'} -%}{%- if "
                                   "params.folder %}{% set _ = b.update({'parents': "
                                   '[params.folder]}) %}{% endif -%}{{ b | tojson }}',
                           'responseMap': {'spreadsheetId': 'id',
                                           'title': 'name',
                                           'webViewLink': 'webViewLink'}},
                  'fields': [{'name': 'title',
                              'label': 'Title',
                              'type': 'String',
                              'required': True},
                             {'name': 'folder',
                              'label': 'Folder',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id',
                              'help': 'Destination Drive folder (Shared Drive). Paste a folder '
                                      'link or id.'}],
                  'output': {'spreadsheetId': 'New spreadsheet id',
                             'title': 'Title',
                             'url': 'Open-in-Sheets URL'}},
                 {'value': 'getValues',
                  'label': 'Get values',
                  'method': 'spreadsheets.values.get',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'GET',
                           'url': 'spreadsheets/{{ params.spreadsheet }}/values/{{ '
                                  'params.range }}',
                           'contentType': 'application/json',
                           'responseMap': {'range': 'range', 'values': 'values'}},
                  'fields': [{'name': 'spreadsheet',
                              'label': 'Spreadsheet',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'range',
                              'label': 'Range (A1)',
                              'type': 'String',
                              'required': True,
                              'default': 'A1:Z1000',
                              'help': 'A1 notation, e.g. Sheet1!A1:D50'}],
                  'output': {'range': 'Resolved range', 'values': '2D array of cell values'}},
                 {'value': 'updateValues',
                  'label': 'Update values',
                  'method': 'spreadsheets.values.update',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'PUT',
                           'url': 'spreadsheets/{{ params.spreadsheet }}/values/{{ '
                                  'params.range }}',
                           'query': {'valueInputOption': '{{ params.valueInputOption or '
                                                         "'USER_ENTERED' }}"},
                           'contentType': 'application/json',
                           'body': '{"values": {{ params["values"] }}}',
                           'responseMap': {'updatedCells': 'updatedCells',
                                           'updatedRange': 'updatedRange'}},
                  'fields': [{'name': 'spreadsheet',
                              'label': 'Spreadsheet',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'range',
                              'label': 'Range (A1)',
                              'type': 'String',
                              'required': True},
                             {'name': 'values',
                              'label': 'Values (JSON 2D array)',
                              'type': 'Text',
                              'required': True,
                              'help': 'e.g. [["Name","Score"],["Ann",42]]'},
                             {'name': 'valueInputOption',
                              'label': 'Input mode',
                              'type': 'Dropdown',
                              'default': 'USER_ENTERED',
                              'choices': [{'label': 'User entered (parse formulas/dates)',
                                           'value': 'USER_ENTERED'},
                                          {'label': 'Raw', 'value': 'RAW'}]}],
                  'output': {'updatedRange': 'Range written',
                             'updatedCells': 'Number of cells updated'}},
                 {'value': 'appendValues',
                  'label': 'Append rows',
                  'method': 'spreadsheets.values.append',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'spreadsheets/{{ params.spreadsheet }}/values/{{ '
                                  "params.range or 'A1' }}:append",
                           'query': {'valueInputOption': '{{ params.valueInputOption or '
                                                         "'USER_ENTERED' }}",
                                     'insertDataOption': 'INSERT_ROWS'},
                           'contentType': 'application/json',
                           'body': '{"values": {{ params["values"] }}}',
                           'responseMap': {'updatedRange': 'updates.updatedRange',
                                           'updatedCells': 'updates.updatedCells'}},
                  'fields': [{'name': 'spreadsheet',
                              'label': 'Spreadsheet',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'range',
                              'label': 'Range (A1)',
                              'type': 'String',
                              'default': 'A1'},
                             {'name': 'values',
                              'label': 'Rows (JSON 2D array)',
                              'type': 'Text',
                              'required': True,
                              'help': 'e.g. [["Ann",42],["Bob",37]]'},
                             {'name': 'valueInputOption',
                              'label': 'Input mode',
                              'type': 'Dropdown',
                              'default': 'USER_ENTERED',
                              'choices': [{'label': 'User entered (parse formulas/dates)',
                                           'value': 'USER_ENTERED'},
                                          {'label': 'Raw', 'value': 'RAW'}]}],
                  'output': {'updatedRange': 'Range written',
                             'updatedCells': 'Number of cells appended'}},
                 {'value': 'clearValues',
                  'label': 'Clear range',
                  'method': 'spreadsheets.values.clear',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'spreadsheets/{{ params.spreadsheet }}/values/{{ '
                                  'params.range }}:clear',
                           'contentType': 'application/json',
                           'body': '{}',
                           'responseMap': {'clearedRange': 'clearedRange'}},
                  'fields': [{'name': 'spreadsheet',
                              'label': 'Spreadsheet',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'range',
                              'label': 'Range (A1)',
                              'type': 'String',
                              'required': True}],
                  'output': {'clearedRange': 'Range cleared'}},
                 {'value': 'addSheet',
                  'label': 'Add sheet (tab)',
                  'method': 'spreadsheets.batchUpdate → addSheet',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'spreadsheets/{{ params.spreadsheet }}:batchUpdate',
                           'contentType': 'application/json',
                           'body': "{{ {'requests': [{'addSheet': {'properties': {'title': "
                                   'params.title}}}]} | tojson }}',
                           'responseMap': {'sheetId': 'replies[0].addSheet.properties.sheetId',
                                           'title': 'replies[0].addSheet.properties.title'}},
                  'fields': [{'name': 'spreadsheet',
                              'label': 'Spreadsheet',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'title',
                              'label': 'Sheet title',
                              'type': 'String',
                              'required': True}],
                  'output': {'spreadsheetId': 'Spreadsheet id',
                             'sheetId': 'New sheet id',
                             'title': 'Sheet title'}}]},
 {'connectorId': 'google_slides',
  'label': 'Google Slides',
  'description': 'Create and edit Google Slides decks — template fill, add/duplicate slides, '
                 'read text.',
  'icon': {'path': 'M3 4h18v2H3zm1 3h16v11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zm2 2v7h12V9z',
           'color': '#fbbc04',
           'label': 'Google Slides'},
  'api': {'name': 'slides',
          'version': 'v1',
          'discovery': 'https://slides.googleapis.com/$discovery/rest?version=v1'},
  'execution': {'type': 'HTTP Request',
                'baseUrl': 'https://slides.googleapis.com/v1',
                'timeout': 30,
                'auth': {'type': 'Service Account JSON',
                         'source': 'On this connector',
                         'headerName': 'X-API-Key',
                         'scopes': 'https://www.googleapis.com/auth/presentations\n'
                                   'https://www.googleapis.com/auth/drive'}},
  'operations': [{'value': 'createPresentation',
                  'label': 'Create presentation',
                  'method': 'files.create (Drive) — see google_slides.create_presentation',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'https://www.googleapis.com/drive/v3/files',
                           'query': {'supportsAllDrives': 'true',
                                     'fields': 'id,name,webViewLink'},
                           'contentType': 'application/json',
                           'body': "{%- set b = {'name': params.title, 'mimeType': "
                                   "'application/vnd.google-apps.presentation'} -%}{%- if "
                                   "params.folder %}{% set _ = b.update({'parents': "
                                   '[params.folder]}) %}{% endif -%}{{ b | tojson }}',
                           'responseMap': {'presentationId': 'id',
                                           'title': 'name',
                                           'webViewLink': 'webViewLink'}},
                  'fields': [{'name': 'folder',
                              'label': 'Folder',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id',
                              'help': 'Destination Drive folder — paste a folder link or id. '
                                      'Must be a Shared Drive folder the service account can '
                                      'write to: a service account has no My Drive quota of '
                                      'its own.'},
                             {'name': 'title',
                              'label': 'Title',
                              'type': 'String',
                              'required': True}],
                  'output': {'presentationId': 'New presentation id',
                             'title': 'Title',
                             'url': 'Open-in-Drive URL'}},
                 {'value': 'replaceAllText',
                  'label': 'Replace all text (deck template fill)',
                  'method': 'presentations.batchUpdate → replaceAllText',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'presentations/{{ params.presentation }}:batchUpdate',
                           'contentType': 'application/json',
                           'body': '{"requests": [{"replaceAllText": {"containsText": {"text": '
                                   '{{ params.find | tojson }}, "matchCase": {{ \'true\' if '
                                   '(params.matchCase | string | lower) in '
                                   "['1','true','yes','on'] else 'false' "
                                   '}}},"replaceText": {{ (params.replace or "") | tojson '
                                   '}}}}]}',
                           'responseMap': {'occurrencesChanged': 'replies[0].replaceAllText.occurrencesChanged'}},
                  'fields': [{'name': 'presentation',
                              'label': 'Presentation',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'find',
                              'label': 'Find text',
                              'type': 'String',
                              'required': True},
                             {'name': 'replace', 'label': 'Replace with', 'type': 'Text'},
                             {'name': 'matchCase', 'label': 'Match case', 'type': 'Boolean'}],
                  'output': {'presentationId': 'Presentation id',
                             'occurrencesChanged': 'Number of replacements'}},
                 {'value': 'createSlide',
                  'label': 'Add slide',
                  'method': 'presentations.batchUpdate → createSlide',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'presentations/{{ params.presentation }}:batchUpdate',
                           'contentType': 'application/json',
                           'body': '{%- set r = {} -%}{%- if params.layout %}{% set _ = '
                                   "r.update({'slideLayoutReference': {'predefinedLayout': "
                                   "params.layout}}) %}{% endif -%}{{ {'requests': "
                                   "[{'createSlide': r}]} | tojson }}",
                           'responseMap': {'slideObjectId': 'replies[0].createSlide.objectId'}},
                  'fields': [{'name': 'presentation',
                              'label': 'Presentation',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'layout',
                              'label': 'Layout',
                              'type': 'Dropdown',
                              'choices': [{'label': 'Blank', 'value': 'BLANK'},
                                          {'label': 'Title', 'value': 'TITLE'},
                                          {'label': 'Title and body',
                                           'value': 'TITLE_AND_BODY'},
                                          {'label': 'Section header',
                                           'value': 'SECTION_HEADER'},
                                          {'label': 'One column text',
                                           'value': 'ONE_COLUMN_TEXT'}]}],
                  'output': {'presentationId': 'Presentation id',
                             'slideObjectId': 'New slide object id'}},
                 {'value': 'duplicateSlide',
                  'label': 'Duplicate slide',
                  'method': 'presentations.batchUpdate → duplicateObject',
                  'executionType': 'HTTP Request',
                  'http': {'method': 'POST',
                           'url': 'presentations/{{ params.presentation }}:batchUpdate',
                           'contentType': 'application/json',
                           'body': "{{ {'requests': [{'duplicateObject': {'objectId': "
                                   'params.slideObjectId}}]} | tojson }}',
                           'responseMap': {'slideObjectId': 'replies[0].duplicateObject.objectId'}},
                  'fields': [{'name': 'presentation',
                              'label': 'Presentation',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'},
                             {'name': 'slideObjectId',
                              'label': 'Slide object id',
                              'type': 'String',
                              'required': True}],
                  'output': {'presentationId': 'Presentation id',
                             'duplicatedObjectId': 'Duplicated slide object id'}},
                 {'value': 'getText',
                  'label': 'Get text',
                  'method': 'presentations.get + walk',
                  'executionType': 'Python Handler',
                  'handlerPath': 'one_bpmn.one_bpmn.connectors.google_slides_ops.get_text',
                  'fields': [{'name': 'presentation',
                              'label': 'Presentation',
                              'type': 'String',
                              'required': True,
                              'transform': 'one_bpmn.one_bpmn.integrations.google_common.normalize_drive_id'}],
                  'output': {'text': 'Plain text across all slides'}}]}]


def execute():
	if not frappe.db.table_exists("BPMN Connector"):
		return

	from one_bpmn.one_bpmn.connectors.manifest import clear_manifest_cache
	from one_bpmn.one_bpmn.connectors.seed import import_manifest

	results = {}
	for manifest in GOOGLE_CONNECTORS:
		results[manifest["connectorId"]] = import_manifest(manifest, overwrite=False)

	clear_manifest_cache()
	frappe.db.commit()

	created = [c for c, state in results.items() if state != "skipped"]
	kept = [c for c, state in results.items() if state == "skipped"]
	if created:
		print(f"Seeded connectors: {', '.join(created)}")
	if kept:
		print(f"Already present, left as configured: {', '.join(kept)}")
