/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BpmnEditor: typeof import('./src/components/BpmnEditor.vue')['default']
    CallActivitySearchDialog: typeof import('./src/components/CallActivitySearchDialog.vue')['default']
    EditorSidebar: typeof import('./src/components/EditorSidebar.vue')['default']
    EditorTabs: typeof import('./src/components/EditorTabs.vue')['default']
    FormattingToolbar: typeof import('./src/components/FormattingToolbar.vue')['default']
    NotificationLinkDialog: typeof import('./src/components/NotificationLinkDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShapeLibraryPanel: typeof import('./src/components/ShapeLibraryPanel.vue')['default']
  }
}
