/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIAgentConfigModal: typeof import('./src/components/AIAgentConfigModal.vue')['default']
    BpmnDiagramViewer: typeof import('./src/components/process_instance/BpmnDiagramViewer.vue')['default']
    BpmnEditor: typeof import('./src/components/BpmnEditor.vue')['default']
    CallActivitySearchDialog: typeof import('./src/components/CallActivitySearchDialog.vue')['default']
    ConfigImportResultsDialog: typeof import('./src/components/ConfigImportResultsDialog.vue')['default']
    DiffViewer: typeof import('./src/components/DiffViewer.vue')['default']
    DmnEditor: typeof import('./src/components/DmnEditor.vue')['default']
    EditorSidebar: typeof import('./src/components/EditorSidebar.vue')['default']
    EditorTabs: typeof import('./src/components/EditorTabs.vue')['default']
    ElementInspector: typeof import('./src/components/process_instance/ElementInspector.vue')['default']
    ExportConfigDialog: typeof import('./src/components/ExportConfigDialog.vue')['default']
    FormattingToolbar: typeof import('./src/components/FormattingToolbar.vue')['default']
    InstanceHeader: typeof import('./src/components/process_instance/InstanceHeader.vue')['default']
    InstanceHistory: typeof import('./src/components/process_instance/InstanceHistory.vue')['default']
    LogixCanvas: typeof import('./src/components/LogixCanvas.vue')['default']
    LogixChat: typeof import('./src/components/LogixChat.vue')['default']
    NotificationLinkDialog: typeof import('./src/components/NotificationLinkDialog.vue')['default']
    PendingActions: typeof import('./src/components/process_instance/PendingActions.vue')['default']
    ProsAllyPanel: typeof import('./src/components/ProsAllyPanel.vue')['default']
    ReadinessChecklistDialog: typeof import('./src/components/ReadinessChecklistDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShapeLibraryPanel: typeof import('./src/components/ShapeLibraryPanel.vue')['default']
    VersionDiffDialog: typeof import('./src/components/VersionDiffDialog.vue')['default']
  }
}
