#!/usr/bin/env node
/**
 * BPMN IR → XML pipeline.
 *
 * Reads an IR JSON document from stdin, runs three deterministic passes:
 *   1. normalizeGateways   — eliminate task/event fan-out and fan-in
 *   2. assertGatewayPairing — reject mismatched opens/closes pairs before compiling
 *   3. compileIRtoBpmn     — build a bpmn-moddle tree, add DI layout
 *
 * For processes WITHOUT lanes: shapes come from bpmn-auto-layout, and the
 * frontend (spiff/src/utils/bpmnLayout.js) regenerates the layout on import.
 * For processes WITH lanes (pools): bpmn-auto-layout lays out only the first
 * participant's process and drops the pool and lane bands entirely (still true
 * at 1.3.0, verified WI-002042), so BPMNDI is generated by buildManualLaneDI(),
 * which the frontend then keeps verbatim.
 *
 * buildManualLaneDI places one node per (lane, column) cell and routes every
 * edge through reserved gutters and strips on allocated channels, so no edge
 * enters a shape it does not connect to and no two shapes overlap. See the
 * comments on the routing model there, and one_bpmn/tests/test_lane_layout.py
 * for the guarantees that are pinned.
 *
 * Writes { ok, xml, problems:[{kind, message}] } to stdout.
 * Semantic validation is handled by the Python bpmn_validator layer.
 *
 * Invoked from bpmn_ir_pipeline.compile_ir() via subprocess.
 */

import { BpmnModdle } from 'bpmn-moddle';

// ── Constants ─────────────────────────────────────────────────────────────────

const GATEWAY_TYPES = new Set([
  'exclusiveGateway', 'parallelGateway', 'inclusiveGateway',
]);

const BPMN_TYPE_MAP = {
  startEvent:       'bpmn:StartEvent',
  endEvent:         'bpmn:EndEvent',
  task:             'bpmn:ScriptTask',       // fallback; normalised IR should never emit bare task
  userTask:         'bpmn:UserTask',
  scriptTask:       'bpmn:ScriptTask',
  serviceTask:      'bpmn:ServiceTask',
  manualTask:       'bpmn:ManualTask',
  businessRuleTask: 'bpmn:BusinessRuleTask',
  exclusiveGateway: 'bpmn:ExclusiveGateway',
  parallelGateway:  'bpmn:ParallelGateway',
  inclusiveGateway: 'bpmn:InclusiveGateway',
  subProcess:       'bpmn:SubProcess',
};

// Layout constants for manual lane DI generation. Lane heights and column
// spacing are no longer fixed: buildManualLaneDI sizes each lane band and each
// column gutter to the routing channels it actually has to carry (WI-002042).
const PARTICIPANT_X    = 150;
const PARTICIPANT_Y    = 80;
const POOL_HEADER_W    = 30;   // vertical pool-name strip (leftmost)
const LANE_HEADER_W    = 30;   // per-lane name strip

// Per-type element dimensions (pixels)
const NODE_DIMS = {
  startEvent:       { w: 36, h: 36 },
  endEvent:         { w: 36, h: 36 },
  exclusiveGateway: { w: 50, h: 50 },
  parallelGateway:  { w: 50, h: 50 },
  inclusiveGateway: { w: 50, h: 50 },
};
const DEFAULT_NODE_DIMS = { w: 100, h: 80 };

function nodeDims(type) {
  return NODE_DIMS[type] || DEFAULT_NODE_DIMS;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function readStdin() {
  return new Promise((resolve, reject) => {
    let buf = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', chunk => { buf += chunk; });
    process.stdin.on('end',  () => resolve(buf));
    process.stdin.on('error', reject);
  });
}

function buildAdjacency(nodes, flows) {
  const out = new Map(nodes.map(n => [n.id, []]));
  const inn = new Map(nodes.map(n => [n.id, []]));
  for (const f of flows) {
    (out.get(f.from) || []).push(f);
    (inn.get(f.to)   || []).push(f);
  }
  return { out, inn };
}

let _seq = 0;
function uid(prefix) { return `${prefix}_${++_seq}`; }

// ── Pass 1: normalizeGateways ─────────────────────────────────────────────────
//
// Invariant enforced: no non-gateway node has >1 incoming or >1 outgoing flow.
//
//   no-implicit-split (task with >1 outgoing) → insert split gateway after node
//   fake-join         (task with >1 incoming) → insert join  gateway before node
//
// Inserted gateways are tagged { inferred: true } so downstream code can
// distinguish them from explicitly modelled gateways.

function normalizeGateways(ir) {
  let nodes = ir.nodes.map(n => ({ ...n }));
  let flows = ir.flows.map(f => ({ ...f }));

  // ── Fan-out pass ──
  {
    const { out } = buildAdjacency(nodes, flows);
    for (const n of [...nodes]) {
      if (GATEWAY_TYPES.has(n.type)) continue;
      const outFlows = out.get(n.id) || [];
      if (outFlows.length <= 1) continue;

      const gwType = outFlows.some(f => f.condition) ? 'exclusiveGateway' : 'parallelGateway';
      const gwId   = uid('gw_split');
      nodes.push({ id: gwId, type: gwType, name: `${n.name} Split`, inferred: true });

      // Repoint: all flows previously sourced from N now come from the new gateway
      flows = flows.map(f => outFlows.includes(f) ? { ...f, from: gwId } : f);
      // Bridge: N → gateway
      flows.push({ from: n.id, to: gwId });

      // Exclusive split must have exactly one default flow.
      // If all outgoing flows carry conditions (no obvious fallback), strip the last
      // one's condition and promote it to the unconditional default path.
      if (gwType === 'exclusiveGateway') {
        if (!flows.filter(f => f.from === gwId).some(f => f.default)) {
          let di = flows.findIndex(f => f.from === gwId && !f.condition && !f.default);
          const mustStrip = di < 0;
          if (di < 0) di = flows.reduce((best, f, i) => (f.from === gwId ? i : best), -1);
          if (di >= 0) {
            flows = flows.map((f, i) => {
              if (i !== di) return f;
              const f2 = { ...f, default: true };
              if (mustStrip) delete f2.condition;
              return f2;
            });
          }
        }
      }
    }
  }

  // ── Fan-in pass (rebuild adjacency after fan-out changes) ──
  {
    const { inn } = buildAdjacency(nodes, flows);
    for (const n of [...nodes]) {
      if (GATEWAY_TYPES.has(n.type)) continue;
      const inFlows = inn.get(n.id) || [];
      if (inFlows.length <= 1) continue;

      const gwId = uid('gw_join');
      nodes.push({ id: gwId, type: 'exclusiveGateway', name: `${n.name} Join`, inferred: true });

      // Repoint: all flows previously targeting N now target the join gateway
      flows = flows.map(f => inFlows.includes(f) ? { ...f, to: gwId } : f);
      // Bridge: join gateway → N
      flows.push({ from: gwId, to: n.id });
    }
  }

  // ── Gateway join-fork pass (rebuild adjacency after prior passes) ──
  // A gateway with >1 incoming AND >1 outgoing violates no-gateway-join-fork.
  // Fix: keep original as the join (N→1), insert a new fork gateway (1→N).
  {
    const { out, inn } = buildAdjacency(nodes, flows);
    for (const n of [...nodes]) {
      if (!GATEWAY_TYPES.has(n.type)) continue;
      const inFlows  = inn.get(n.id) || [];
      const outFlows = out.get(n.id) || [];
      if (inFlows.length <= 1 || outFlows.length <= 1) continue;

      // If none of the outgoing flows carry conditions or a default, the original gateway
      // had no routing logic — make the fork parallel so all paths run concurrently and
      // no conditional-flows check fires on the inferred fork.
      const forkType = outFlows.some(f => f.condition || f.default) ? n.type : 'parallelGateway';
      const forkId = uid('gw_fork');
      nodes.push({ id: forkId, type: forkType, name: `${n.name} Fork`, inferred: true });

      // All outgoing flows from original now come from the fork gateway
      flows = flows.map(f => outFlows.includes(f) ? { ...f, from: forkId } : f);
      // Bridge: join → fork
      flows.push({ from: n.id, to: forkId });

      // Exclusive fork must have exactly one default flow (same robust logic as fan-out pass).
      if (forkType === 'exclusiveGateway') {
        if (!flows.filter(f => f.from === forkId).some(f => f.default)) {
          let di = flows.findIndex(f => f.from === forkId && !f.condition && !f.default);
          const mustStrip = di < 0;
          if (di < 0) di = flows.reduce((best, f, i) => (f.from === forkId ? i : best), -1);
          if (di >= 0) {
            flows = flows.map((f, i) => {
              if (i !== di) return f;
              const f2 = { ...f, default: true };
              if (mustStrip) delete f2.condition;
              return f2;
            });
          }
        }
      }
    }
  }

  // ── Cleanup pass: remove superfluous gateways (1 in + 1 out) ──
  // normalizeGateways may insert join/fork gateways that end up unnecessary
  // when the IR structure doesn't actually require them (e.g. a join gateway
  // inserted for a node that only has one actual predecessor after other
  // normalization). Remove them and bridge predecessor → successor directly.
  {
    let changed = true;
    while (changed) {
      changed = false;
      const { out, inn } = buildAdjacency(nodes, flows);
      for (const n of [...nodes]) {
        if (!GATEWAY_TYPES.has(n.type)) continue;
        const inFlows  = inn.get(n.id) || [];
        const outFlows = out.get(n.id) || [];
        if (inFlows.length !== 1 || outFlows.length !== 1) continue;

        // This gateway is superfluous: exactly 1 in, 1 out
        const predFlow = inFlows[0];   // { from, to, ... }
        const succFlow = outFlows[0];  // { from, to, ... }

        // Bridge: predecessor → successor (preserve name/condition from the outgoing flow)
        const bridgeFlow = {
          from: predFlow.from,
          to:   succFlow.to,
          name: succFlow.name || predFlow.name || '',
        };
        if (succFlow.condition) bridgeFlow.condition = succFlow.condition;
        if (succFlow.default)   bridgeFlow.default   = succFlow.default;

        // Remove the two old flows and the gateway node
        flows = flows.filter(f => f !== predFlow && f !== succFlow);
        flows.push(bridgeFlow);
        nodes = nodes.filter(nd => nd.id !== n.id);
        changed = true;
        break;  // restart scan since adjacency changed
      }
    }
  }

  return { ...ir, nodes, flows };
}

// ── Post-normalization structural check ───────────────────────────────────────
//
// After all three normalizeGateways passes, every non-gateway node must have
// at most 1 outgoing and at most 1 incoming flow.  If any remain it means
// normalizeGateways has an unhandled edge case — surface it immediately so the
// Python repair loop can handle it rather than silently producing bad XML.

function assertNoImplicitSplitOrJoin(ir) {
  const problems = [];
  const { out, inn } = buildAdjacency(ir.nodes, ir.flows);
  for (const n of ir.nodes) {
    if (GATEWAY_TYPES.has(n.type)) continue;
    const outCount = (out.get(n.id) || []).length;
    const inCount  = (inn.get(n.id) || []).length;
    if (outCount > 1) {
      problems.push({
        kind: 'lint', rule: 'no-implicit-split', elementId: n.id,
        message: `Node "${n.id}" (${n.type}) still has ${outCount} outgoing flows after normalisation — normalizeGateways bug.`,
      });
    }
    if (inCount > 1) {
      problems.push({
        kind: 'lint', rule: 'fake-join', elementId: n.id,
        message: `Node "${n.id}" (${n.type}) still has ${inCount} incoming flows after normalisation — normalizeGateways bug.`,
      });
    }
  }
  return problems;
}

// ── Lane-assignment structural check ─────────────────────────────────────────
//
// When ir.lanes is present, every non-inferred node MUST declare a "lane" field
// whose value is a valid lane id.  Inferred gateways (inserted by normalizeGateways)
// are exempt — their lane is resolved later by propagation in buildManualLaneDI.
//
// Also checks that no sequence flow crosses pool boundaries (only relevant once
// multi-pool diagrams are supported; currently always satisfied, checked defensively).

function assertLaneAssignment(ir) {
  if (!ir.lanes || !ir.lanes.length) return [];
  const laneIds = new Set(ir.lanes.map(l => l.id));
  const problems = [];

  for (const n of ir.nodes) {
    if (n.inferred) continue;       // compiler-generated; lane set via propagation
    if (!n.lane) {
      problems.push({
        kind: 'structure', rule: 'lane-orphan', elementId: n.id,
        message: `Node "${n.id}" (${n.type}: "${n.name}") has no "lane" field. ` +
          `Every node must be assigned to a lane when lanes are defined. ` +
          `Valid lane ids: ${[...laneIds].join(', ')}.`,
      });
    } else if (!laneIds.has(n.lane)) {
      problems.push({
        kind: 'structure', rule: 'lane-orphan', elementId: n.id,
        message: `Node "${n.id}" (${n.type}: "${n.name}") references unknown lane "${n.lane}". ` +
          `Valid lane ids: ${[...laneIds].join(', ')}.`,
      });
    }
  }
  return problems;
}

// ── Pass 2: assertGatewayPairing ──────────────────────────────────────────────
//
// A node with `closes: "<splitId>"` declares it is the join counterpart of that
// split. The types must match: a parallelGateway split must be closed by a
// parallelGateway join. Mismatch passes bpmnlint but deadlocks Spiff at runtime.
// This pass rejects before compiling so the error reaches the LLM repair loop.

function assertGatewayPairing(ir) {
  const problems = [];
  const nodeMap  = new Map(ir.nodes.map(n => [n.id, n]));

  for (const n of ir.nodes) {
    if (!n.closes) continue;
    const split = nodeMap.get(n.closes);
    if (!split) {
      problems.push({
        kind:    'pairing',
        message: `Node "${n.id}" (${n.name}) declares closes="${n.closes}" but that node does not exist.`,
      });
    } else if (split.type !== n.type) {
      problems.push({
        kind:    'pairing',
        message:
          `Gateway pairing mismatch: "${n.id}" (type=${n.type}) closes "${split.id}" (type=${split.type}). ` +
          `A ${split.type} split must be closed by a ${split.type} join, not a ${n.type}.`,
      });
    }
  }

  return problems;
}

// ── Pass 3: compileIRtoBpmn ───────────────────────────────────────────────────
//
// Deterministic: same IR always produces the same moddle tree.
// Stable IDs are used as-is from the IR; flow IDs are derived from source+target+index.
// Incoming/outgoing refs and default pointers are wired exactly once.

async function compileIRtoBpmn(ir) {
  const moddle       = new BpmnModdle();
  const flowElements = [];
  const elementById  = new Map();

  // 1. Semantic nodes
  // Do NOT pass incoming/outgoing arrays — bpmn-moddle auto-wires them through the
  // sourceRef/targetRef inverse associations when it processes the Process flowElements.
  // Passing them AND manually pushing causes each flow to appear twice in the output.
  for (const n of ir.nodes) {
    const bpmnType = BPMN_TYPE_MAP[n.type] || 'bpmn:ScriptTask';
    const el = moddle.create(bpmnType, { id: n.id, name: n.name });
    elementById.set(n.id, el);
    flowElements.push(el);
  }

  // 2. Sequence flows — setting sourceRef/targetRef is sufficient; moddle wires
  // the inverse incoming/outgoing references automatically via its type descriptors.
  const seqMeta = [];
  for (let i = 0; i < ir.flows.length; i++) {
    const f   = ir.flows[i];
    const src = elementById.get(f.from);
    const tgt = elementById.get(f.to);
    if (!src || !tgt) continue;

    const sf = moddle.create('bpmn:SequenceFlow', {
      id:        `flow_${f.from}_${f.to}_${i}`,
      name:      f.name || '',
      sourceRef: src,
      targetRef: tgt,
    });

    if (f.condition) {
      sf.conditionExpression = moddle.create('bpmn:FormalExpression', { body: f.condition });
    }

    flowElements.push(sf);
    seqMeta.push({ sf, f });
  }

  // 3. Wire default flows on exclusive / inclusive gateways
  for (const { sf, f } of seqMeta) {
    if (f.default) {
      const src = elementById.get(f.from);
      if (src) src.default = sf;
    }
  }

  // 4. Lane set (optional) — lanes is [{ id, name, role? }]
  let laneSets;
  if (ir.lanes && ir.lanes.length) {
    const laneEls = ir.lanes.map(lane => {
      const flowNodeRef = (ir.nodes || [])
        .filter(n => n.lane === lane.id)
        .map(n => elementById.get(n.id))
        .filter(Boolean);
      return moddle.create('bpmn:Lane', { id: lane.id, name: lane.name, flowNodeRef });
    });
    laneSets = [moddle.create('bpmn:LaneSet', { id: 'LaneSet_1', lanes: laneEls })];
  }

  // 5. Process
  const processEl = moddle.create('bpmn:Process', {
    id:           'Process_1',
    isExecutable: true,
    flowElements,
    ...(laneSets ? { laneSets } : {}),
  });

  // 6. Collaboration + Participant (required for bpmn-js to render swim lanes)
  const rootElements = [processEl];
  if (laneSets) {
    const participantEl = moddle.create('bpmn:Participant', {
      id:         'Participant_1',
      name:       ir.name || 'Process',
      processRef: processEl,
    });
    const collaborationEl = moddle.create('bpmn:Collaboration', {
      id:           'Collaboration_1',
      participants: [participantEl],
    });
    rootElements.unshift(collaborationEl);  // collaboration must come first
  }

  const definitions = moddle.create('bpmn:Definitions', {
    id:              'Definitions_1',
    targetNamespace: 'http://bpmn.io/schema/bpmn',
    exporter:        'processa-pipeline',
    exporterVersion: '1.0',
    rootElements,
  });

  const { xml } = await moddle.toXML(definitions, { format: true });
  return xml;
}

// ── Manual DI builder for lane-based processes ────────────────────────────────
//
// bpmn-auto-layout v0.4.0 explicitly does not support Pools.
// When ir.lanes is present we skip auto-layout and generate BPMNDI ourselves.
//
// Algorithm:
//   1. Propagate lane assignments to inferred gateways (no explicit lane field)
//   2. Topological column assignment: longest-path BFS so elements flow left→right
//   3. Within each (lane, column) cell, stack elements vertically
//   4. Emit BPMNDiagram XML: participant → lanes → node shapes → edge waypoints

function buildManualLaneDI(ir) {
  const lanes = ir.lanes || [];   // [{ id, name, role? }]
  if (!lanes.length) return '';

  const laneIndexById = new Map(lanes.map((l, i) => [l.id, i]));
  const nodeMap       = new Map(ir.nodes.map(n => [n.id, n]));

  // Build adjacency for lane propagation and column assignment
  const adjOut = new Map(ir.nodes.map(n => [n.id, []]));
  const adjInn = new Map(ir.nodes.map(n => [n.id, []]));
  for (const f of ir.flows) {
    if (adjOut.has(f.from)) adjOut.get(f.from).push(f.to);
    if (adjInn.has(f.to))   adjInn.get(f.to).push(f.from);
  }

  // Propagate lane id to inferred gateways (no explicit lane field).
  // Iterates until stable so multi-hop chains resolve correctly.
  const nodeLaneId = new Map();
  for (const n of ir.nodes) {
    if (n.lane) nodeLaneId.set(n.id, n.lane);
  }
  let changed = true;
  while (changed) {
    changed = false;
    for (const n of ir.nodes) {
      if (nodeLaneId.has(n.id)) continue;
      const neighbours = (adjInn.get(n.id) || []).concat(adjOut.get(n.id) || []);
      for (const nb of neighbours) {
        if (nodeLaneId.has(nb)) {
          nodeLaneId.set(n.id, nodeLaneId.get(nb));
          changed = true;
          break;
        }
      }
    }
  }
  // Final fallback: unresolved nodes go to first lane
  for (const n of ir.nodes) {
    if (!nodeLaneId.has(n.id) && lanes.length) nodeLaneId.set(n.id, lanes[0].id);
  }

  // ── Back-edge detection via iterative DFS from start ─────────────────────
  // Kahn's topological sort fails on cyclic flows (loops, re-check paths).
  // We detect back edges first so the column assignment treats the process as a
  // DAG, placing nodes in a proper left-to-right sequence.  Back edges are still
  // drawn as arrows; they just arc back to an earlier column.
  const startNodeId = (ir.nodes.find(n => n.type === 'startEvent') || ir.nodes[0] || {}).id;
  const backEdges   = new Set();  // "from:to" key strings

  if (startNodeId) {
    const dfsVisited = new Set([startNodeId]);
    const dfsInStack = new Set([startNodeId]);
    // Each frame: [nodeId, nextChildIndex]
    const dfsStack   = [[startNodeId, 0]];

    while (dfsStack.length) {
      const frame    = dfsStack[dfsStack.length - 1];
      const nodeId   = frame[0];
      const children = adjOut.get(nodeId) || [];

      if (frame[1] >= children.length) {
        dfsInStack.delete(nodeId);
        dfsStack.pop();
      } else {
        const nextId = children[frame[1]++];
        if (dfsInStack.has(nextId)) {
          backEdges.add(nodeId + ':' + nextId);   // cycle → back edge
        } else if (!dfsVisited.has(nextId)) {
          dfsVisited.add(nextId);
          dfsInStack.add(nextId);
          dfsStack.push([nextId, 0]);
        }
      }
    }
  }

  // ── Column assignment: one node per (lane, column) cell ──────────────────
  //
  // Walk the DAG in topological order (back edges excluded) and place each node
  // in the first FREE cell at or after max(predecessor column) + 1.
  //
  // The previous version was a plain longest-path DP, which let any number of
  // nodes share a cell and then squeezed them into the lane band by dividing its
  // height between them. On a real map that is ruinous: 46 nodes over 9 columns
  // put fifteen nodes in one cell, so the band stretched to ~1700px, every edge
  // needed long vertical travel, and shapes were metres apart from the lane they
  // belonged to. Reserving a cell per node keeps the diagram a left-to-right
  // flow — which is also what makes "no shape overlaps another shape" true by
  // construction rather than by validation.
  //
  // Nodes in DIFFERENT lanes still share a column: that is genuine concurrency
  // and reads correctly.
  const laneIdxOf = (id) => {
    const lid = nodeLaneId.get(id) || lanes[0].id;
    return laneIndexById.has(lid) ? laneIndexById.get(lid) : 0;
  };

  const inDeg = new Map(ir.nodes.map(n => [n.id, 0]));
  for (const f of ir.flows) {
    if (backEdges.has(f.from + ':' + f.to)) continue;   // skip back edges
    if (inDeg.has(f.to)) inDeg.set(f.to, (inDeg.get(f.to) || 0) + 1);
  }
  const queue = ir.nodes.filter(n => inDeg.get(n.id) === 0).map(n => n.id);
  const ordered = [];
  const seen = new Set(queue);
  let qi = 0;
  while (qi < queue.length) {
    const id = queue[qi++];
    ordered.push(id);
    for (const succId of (adjOut.get(id) || [])) {
      if (backEdges.has(id + ':' + succId)) continue;
      const deg = (inDeg.get(succId) || 1) - 1;
      inDeg.set(succId, deg);
      if (deg === 0 && !seen.has(succId)) { seen.add(succId); queue.push(succId); }
    }
  }
  // Anything the walk never reached (a cycle with no acyclic entry point) still
  // has to be placed, or it would silently pile up in column 0.
  for (const n of ir.nodes) if (!seen.has(n.id)) ordered.push(n.id);

  const col   = new Map();
  const taken = new Set();   // "laneIdx:col" — occupied cells
  for (const id of ordered) {
    let c = 0;
    for (const predId of (adjInn.get(id) || [])) {
      if (backEdges.has(predId + ':' + id)) continue;
      if (col.has(predId)) c = Math.max(c, col.get(predId) + 1);
    }
    const li = laneIdxOf(id);
    while (taken.has(li + ':' + c)) c++;
    taken.add(li + ':' + c);
    col.set(id, c);
  }
  for (const n of ir.nodes) { if (!col.has(n.id)) col.set(n.id, 0); }

  const maxCol = ir.nodes.reduce((m, n) => Math.max(m, col.get(n.id) || 0), 0);

  // Group nodes by (laneIdx, col) cell for vertical stacking
  const groups = new Map();  // key "li:c" → { li, c, nodeIds[] }
  for (const n of ir.nodes) {
    const lid = nodeLaneId.get(n.id) || lanes[0].id;
    const li  = laneIndexById.has(lid) ? laneIndexById.get(lid) : 0;
    const c   = col.get(n.id) || 0;
    const k   = li + ':' + c;
    if (!groups.has(k)) groups.set(k, { li, c, nodeIds: [] });
    groups.get(k).nodeIds.push(n.id);
  }

  // ── Channel routing model (WI-002042) ────────────────────────────────────
  //
  // Nodes sit on a (lane, column, row) grid. The space BETWEEN those cells is
  // reserved and never occupied by a shape: a vertical GUTTER between adjacent
  // columns, and a horizontal STRIP along the bottom of each lane. Every pixel
  // of edge travel happens inside one of them, so an edge can never cross a
  // shape it does not connect to.
  //
  // Two edges sharing a gutter or strip are given different CHANNELS, so they
  // never render as one line. Channels are allocated by occupancy — greedy
  // interval colouring over the ordinal grid — not by the flow's array index.
  // The previous generator offset overlapping edges by `(i % 3) * 10`, giving
  // three channels 10px apart chosen by position in the array, which is why
  // return edges piled onto each other and onto the lane's own node rows.
  //
  // Allocation runs on ORDINAL coordinates (row ordinals, column indices),
  // which are monotonic in pixels, so the channel counts are known before any
  // pixel is computed and the whole layout resolves in a single pass.
  const CH_SP        = 14;   // gap between neighbouring channels in a gutter/strip
  const GUTTER_BASE  = 70;   // clear space between node columns before channels
  const ROW_PITCH    = 110;  // vertical pitch of node rows inside a lane
  const ROW_BAND     = 80;   // tallest node; rows share this centreline
  const LANE_PAD_TOP = 28;
  const LANE_PAD_BOT = 16;
  const STRIP_BASE   = 28;   // clear space in a lane's routing strip

  // Row index of each node within its (lane, column) cell.
  const rowOf = new Map();
  for (const grp of groups.values()) grp.nodeIds.forEach((id, r) => rowOf.set(id, r));

  const laneRows = lanes.map((_, li) => {
    let m = 1;
    for (const g of groups.values()) if (g.li === li) m = Math.max(m, g.nodeIds.length);
    return m;
  });

  // Column width is the widest node in that column, so every column is a clean
  // vertical band and the gutters either side of it stay shape-free.
  const colW = [];
  for (let c = 0; c <= maxCol; c++) colW[c] = 36;
  for (const n of ir.nodes) {
    const c = col.get(n.id) || 0;
    colW[c] = Math.max(colW[c], nodeDims(n.type).w);
  }

  // Ordinal vertical axis: every lane contributes its node rows plus one slot
  // for its routing strip, so ordinals increase monotonically down the pool.
  const laneRowOffset = [];
  let ordAcc = 0;
  for (let li = 0; li < lanes.length; li++) { laneRowOffset.push(ordAcc); ordAcc += laneRows[li] + 1; }
  const ordOf    = (li, row) => laneRowOffset[li] + row;
  const ordStrip = (li)      => laneRowOffset[li] + laneRows[li];

  const occupied = new Set();
  for (const grp of groups.values()) {
    grp.nodeIds.forEach((id, r) => occupied.add(grp.li + ':' + grp.c + ':' + r));
  }
  // Can an edge run straight along this row between these columns?
  const rowClear = (li, row, cFrom, cTo) => {
    for (let c = cFrom; c <= cTo; c++) if (occupied.has(li + ':' + c + ':' + row)) return false;
    return true;
  };

  // ── Plan every edge on the grid, before any pixel exists ──────────────────
  const vRuns = [];   // vertical runs, keyed by gutter index
  const hRuns = [];   // horizontal runs, keyed by lane index (its strip)
  const plans = [];
  for (const f of ir.flows) {
    if (!nodeMap.has(f.from) || !nodeMap.has(f.to)) { plans.push(null); continue; }
    const sl = laneIdxOf(f.from), tl = laneIdxOf(f.to);
    const sc = col.get(f.from) || 0, tc = col.get(f.to) || 0;
    const sr = rowOf.get(f.from) || 0, tr = rowOf.get(f.to) || 0;
    const p = { f, sl, tl, sc, tc, sr, tr };

    if (tc > sc && sl === tl && sr === tr && rowClear(tl, tr, sc + 1, tc - 1)) {
      // Same row, nothing in the way — the plain left-to-right arrow.
      p.kind = 'straight';
    } else if (tc > sc && (tc === sc + 1 || rowClear(tl, tr, sc + 1, tc - 1))) {
      // Forward hop: drop through the gutter immediately right of the source,
      // then run in along the target's own row, which we know is clear.
      p.kind = 'elbow';
      p.g1 = sc;
      p.v1 = {
        key: sc,
        lo: Math.min(ordOf(sl, sr), ordOf(tl, tr)),
        hi: Math.max(ordOf(sl, sr), ordOf(tl, tr)),
      };
      vRuns.push(p.v1);
    } else {
      // Blocked forward hop, or a back edge. Travel horizontally in a routing
      // strip rather than across the diagram body: the target's own strip going
      // forward, and for a back edge the strip of the LOWER of the two lanes, so
      // a loop inside one lane stays inside that lane instead of arcing over the
      // whole pool.
      p.kind = 'strip';
      // The TARGET lane's strip, forwards and backwards alike: the edge then
      // makes its long horizontal run in the band it is already heading for and
      // arrives with a short vertical. Measured against the alternatives on the
      // Fuel Requisition map (avoidable crossings): target lane 228, source lane
      // 285, lower of the two 287, one shared bus below the pool 392 — a shared
      // bus is worst because every lane-changing edge in the diagram then has to
      // cross it.
      p.rl = tl;
      p.g1 = sc;
      p.g2 = tc - 1;
      const so = ordStrip(p.rl);
      p.v1 = { key: p.g1, lo: Math.min(ordOf(sl, sr), so), hi: Math.max(ordOf(sl, sr), so) };
      p.v2 = { key: p.g2, lo: Math.min(ordOf(tl, tr), so), hi: Math.max(ordOf(tl, tr), so) };
      p.h1 = { key: p.rl, lo: Math.min(p.g1, p.g2), hi: Math.max(p.g1, p.g2) };
      vRuns.push(p.v1, p.v2);
      hRuns.push(p.h1);
    }
    plans.push(p);
  }

  // Channel allocation by interval NESTING, then first fit.
  //
  // Runs are sorted narrowest-first, so a run always lands on a channel at or
  // below any run that contains it. That ordering is what actually removes
  // crossings: if run A's span is nested inside run B's, A only ever travels out
  // to its own channel, which is nearer the nodes than B's, so A's two vertical
  // legs stop short of B's horizontal and the two never meet. Only genuinely
  // interleaved spans — the ones no planar drawing can separate either — are
  // left crossing.
  //
  // Sorting by position instead (the obvious first-fit) packs channels just as
  // tightly but shuffles nested runs above their containers, which manufactures
  // crossings that the geometry did not require: it cost ~460 avoidable
  // crossings on the Fuel Requisition map.
  //
  // Within a channel, runs that do not overlap at all still share it, so the
  // gutter or strip stays as narrow as the traffic allows.
  const allocate = (runs) => {
    const byKey = new Map();
    for (const r of runs) {
      if (!byKey.has(r.key)) byKey.set(r.key, []);
      byKey.get(r.key).push(r);
    }
    const counts = new Map();
    for (const [k, list] of byKey) {
      list.sort((a, b) => (a.hi - a.lo) - (b.hi - b.lo) || a.lo - b.lo);
      const channels = [];   // channels[i] = intervals already placed there
      for (const r of list) {
        let i = 0;
        for (; i < channels.length; i++) {
          if (!channels[i].some(o => o.lo < r.hi && r.lo < o.hi)) break;
        }
        if (i === channels.length) channels.push([]);
        channels[i].push(r);
        r.ch = i;
      }
      counts.set(k, channels.length);
    }
    return counts;
  };
  const gutterCount = allocate(vRuns);
  const stripCount  = allocate(hRuns);

  // ── Pixels: gutters and strips are sized to the channels they must hold ───
  const gutterW = (g)  => Math.max(GUTTER_BASE, 40 + (gutterCount.get(g) || 0) * CH_SP);
  const stripH  = (li) => Math.max(STRIP_BASE, 14 + (stripCount.get(li) || 0) * CH_SP);

  const contentLeft = PARTICIPANT_X + POOL_HEADER_W + LANE_HEADER_W;
  const colLeft = [];
  let penX = contentLeft + gutterW(-1);
  for (let c = 0; c <= maxCol; c++) { colLeft[c] = penX; penX += colW[c] + gutterW(c); }

  const gutterStart = (g) => (g < 0 ? contentLeft : colLeft[g] + colW[g]);
  const gutterX = (g, ch) => Math.round(gutterStart(g) + 20 + ch * CH_SP);

  const laneH = lanes.map((_, li) =>
    LANE_PAD_TOP + laneRows[li] * ROW_PITCH + stripH(li) + LANE_PAD_BOT);
  const laneTopY = [];
  let yOff = PARTICIPANT_Y;
  for (let i = 0; i < lanes.length; i++) { laneTopY.push(yOff); yOff += laneH[i]; }
  const totalH       = yOff - PARTICIPANT_Y;
  const participantW = penX - PARTICIPANT_X;

  const rowCenterY = (li, row) => laneTopY[li] + LANE_PAD_TOP + row * ROW_PITCH + ROW_BAND / 2;
  const stripY = (li, ch) =>
    Math.round(laneTopY[li] + LANE_PAD_TOP + laneRows[li] * ROW_PITCH + 14 + ch * CH_SP);

  // Every node centred in its column and on its row's centreline: rows cannot
  // overlap (ROW_PITCH exceeds the tallest node) and columns cannot either.
  const nodePos = new Map();  // nodeId → { x, y, w, h }
  for (const grp of groups.values()) {
    grp.nodeIds.forEach((nid, r) => {
      const d = nodeDims(nodeMap.get(nid).type);
      nodePos.set(nid, {
        x: Math.round(colLeft[grp.c] + (colW[grp.c] - d.w) / 2),
        y: Math.round(rowCenterY(grp.li, r) - d.h / 2),
        w: d.w,
        h: d.h,
      });
    });
  }

  // ── Y-bounds validation ───────────────────────────────────────────────────────
  // Every node's rendered shape must fall inside its assigned lane band.
  // By construction our layout algorithm guarantees this; the check acts as a
  // safety net that catches wrong lane assignments or future layout-algorithm bugs.
  const boundProblems = [];
  for (const n of ir.nodes) {
    const pos = nodePos.get(n.id);
    if (!pos) continue;
    const lid = nodeLaneId.get(n.id) || (lanes.length ? lanes[0].id : '');
    const li  = laneIndexById.has(lid) ? laneIndexById.get(lid) : 0;
    const bandTop    = laneTopY[li];
    const bandBottom = bandTop + laneH[li];
    if (pos.y < bandTop - 1 || pos.y + pos.h > bandBottom + 1) {
      boundProblems.push({
        kind: 'structure', rule: 'lane-bounds', elementId: n.id,
        message: `Node "${n.id}" Y-bounds [${pos.y}–${pos.y + pos.h}] fall outside ` +
          `lane "${lid}" band [${bandTop}–${bandBottom}]. ` +
          `Change this node's "lane" field to the correct lane id.`,
      });
    }
  }
  if (boundProblems.length) return { diSection: '', problems: boundProblems };

  // ── Serialise BPMNDI XML ──────────────────────────────────────────────────────
  const lines = [];
  lines.push('  <bpmndi:BPMNDiagram id="BPMNDiagram_1">');
  lines.push('    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1">');

  // Participant (pool) shape
  lines.push('      <bpmndi:BPMNShape id="Participant_1_di" bpmnElement="Participant_1" isHorizontal="true">');
  lines.push('        <dc:Bounds x="' + PARTICIPANT_X + '" y="' + PARTICIPANT_Y +
             '" width="' + participantW + '" height="' + totalH + '" />');
  lines.push('      </bpmndi:BPMNShape>');

  // Lane shapes — bands tile exactly (heights sum to pool inner height)
  for (let i = 0; i < lanes.length; i++) {
    const lane = lanes[i];
    const laneX = PARTICIPANT_X + POOL_HEADER_W;
    const laneW = participantW - POOL_HEADER_W;
    lines.push('      <bpmndi:BPMNShape id="' + lane.id + '_di" bpmnElement="' + lane.id + '" isHorizontal="true">');
    lines.push('        <dc:Bounds x="' + laneX + '" y="' + laneTopY[i] +
               '" width="' + laneW + '" height="' + laneH[i] + '" />');
    lines.push('      </bpmndi:BPMNShape>');
  }

  // Node shapes
  for (const n of ir.nodes) {
    const pos = nodePos.get(n.id);
    if (!pos) continue;
    const isCompact = (n.type === 'startEvent' || n.type === 'endEvent' || GATEWAY_TYPES.has(n.type));
    lines.push('      <bpmndi:BPMNShape id="' + n.id + '_di" bpmnElement="' + n.id + '">');
    lines.push('        <dc:Bounds x="' + pos.x + '" y="' + pos.y +
               '" width="' + pos.w + '" height="' + pos.h + '" />');
    if (isCompact) {
      const lblX = Math.round(pos.x + pos.w / 2 - 25);
      const lblY = pos.y + pos.h + 2;
      lines.push('        <bpmndi:BPMNLabel>');
      lines.push('          <dc:Bounds x="' + lblX + '" y="' + lblY + '" width="50" height="14" />');
      lines.push('        </bpmndi:BPMNLabel>');
    }
    lines.push('      </bpmndi:BPMNShape>');
  }

  // Label collision test: an edge label must not land on another label, nor on
  // a shape it has nothing to do with. Seeded with every node shape so the very
  // first label already avoids them.
  const labelBoxes = [];
  const boxHit = (a, b) =>
    a.x < b.x + b.w && b.x < a.x + a.w && a.y < b.y + b.h && b.y < a.y + a.h;

  // ── Sequence-flow edges ───────────────────────────────────────────────────
  // Every segment rides a channel allocated above, so no segment can enter a
  // shape it does not connect to and no two segments can share a line.
  for (let i = 0; i < ir.flows.length; i++) {
    const p = plans[i];
    if (!p) continue;
    const f   = p.f;
    const src = nodePos.get(f.from);
    const tgt = nodePos.get(f.to);
    if (!src || !tgt) continue;

    // Always leave the right edge and arrive at the left edge: the direction of
    // travel then reads consistently everywhere on the canvas.
    const sx = src.x + src.w;
    const sy = Math.round(src.y + src.h / 2);
    const tx = tgt.x;
    const ty = Math.round(tgt.y + tgt.h / 2);

    let pts;
    if (p.kind === 'straight' || (p.kind === 'elbow' && sy === ty)) {
      pts = [[sx, sy], [tx, ty]];
    } else if (p.kind === 'elbow') {
      const gx = gutterX(p.g1, p.v1.ch);
      pts = [[sx, sy], [gx, sy], [gx, ty], [tx, ty]];
    } else {
      const g1x = gutterX(p.g1, p.v1.ch);
      const g2x = gutterX(p.g2, p.v2.ch);
      const hy  = stripY(p.rl, p.h1.ch);
      pts = [[sx, sy], [g1x, sy], [g1x, hy], [g2x, hy], [g2x, ty], [tx, ty]];
    }

    const flowId = 'flow_' + f.from + '_' + f.to + '_' + i;
    lines.push('      <bpmndi:BPMNEdge id="' + flowId + '_di" bpmnElement="' + flowId + '">');
    for (const pt of pts) {
      lines.push('        <di:waypoint x="' + pt[0] + '" y="' + pt[1] + '" />');
    }

    // Name the flow on its longest horizontal run — which is a routing channel,
    // so the label sits in reserved space rather than on top of the diagram.
    // Without an explicit BPMNLabel bpmn-js drops every label at the edge
    // midpoint, so labels of flows converging on one gateway land on each other.
    if (f.name) {
      let best = null;
      for (let k = 1; k < pts.length; k++) {
        if (pts[k][1] !== pts[k - 1][1]) continue;
        const len = Math.abs(pts[k][0] - pts[k - 1][0]);
        if (!best || len > best.len) {
          best = { len, cx: (pts[k][0] + pts[k - 1][0]) / 2, cy: pts[k][1] };
        }
      }
      if (!best) best = { cx: pts[0][0], cy: (pts[0][1] + pts[pts.length - 1][1]) / 2 };

      const lw = Math.min(150, Math.max(28, f.name.length * 6 + 8));
      const box = { x: Math.round(best.cx - lw / 2), y: Math.round(best.cy - 19), w: lw, h: 14 };
      // Step off the channel until the slot is free; give up rather than drift
      // far from the edge it names.
      for (let guard = 0; guard < 10; guard++) {
        let clash = false;
        for (const b of labelBoxes) if (boxHit(box, b)) { clash = true; break; }
        if (!clash) {
          for (const q of nodePos.values()) if (boxHit(box, q)) { clash = true; break; }
        }
        if (!clash) break;
        box.y -= 16;
      }
      labelBoxes.push(box);
      lines.push('        <bpmndi:BPMNLabel>');
      lines.push('          <dc:Bounds x="' + box.x + '" y="' + box.y +
                 '" width="' + box.w + '" height="' + box.h + '" />');
      lines.push('        </bpmndi:BPMNLabel>');
    }
    lines.push('      </bpmndi:BPMNEdge>');
  }

  lines.push('    </bpmndi:BPMNPlane>');
  lines.push('  </bpmndi:BPMNDiagram>');
  return { diSection: lines.join('\n'), problems: [] };
}

// Inject BPMNDI section + required namespace declarations into moddle-generated XML.
// moddle omits bpmndi/dc/di namespaces when no DI elements exist in the model tree.
function injectLaneDI(xml, diSection) {
  let result = xml;
  if (result.indexOf('xmlns:bpmndi=') === -1) {
    result = result.replace(
      /(<bpmn:definitions)(\s)/,
      '$1' +
      ' xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"' +
      ' xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"' +
      ' xmlns:di="http://www.omg.org/spec/DD/20100524/DI"' +
      '$2'
    );
  }
  return result.replace('</bpmn:definitions>', diSection + '\n</bpmn:definitions>');
}

// ── Auto-layout (adds BPMNDI for non-lane processes) ─────────────────────────

async function addAutoLayout(xml) {
  try {
    const mod = await import('bpmn-auto-layout');
    const layoutProcess = mod.layoutProcess || (mod.default && mod.default.layoutProcess);
    if (typeof layoutProcess === 'function') return await layoutProcess(xml);
    // Older API: new BpmnAutoLayout().layout(xml)
    const BpmnAutoLayout = mod.default || mod;
    const { xml: laid } = await new BpmnAutoLayout().layout(xml);
    return laid;
  } catch {
    // bpmn-auto-layout not available; Python validator will report no-bpmndi if DI is missing.
    return xml;
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  let ir;
  try {
    ir = JSON.parse(await readStdin());
  } catch (err) {
    process.stdout.write(JSON.stringify({
      ok: false, xml: '',
      problems: [{ kind: 'parse', message: `IR JSON parse error: ${err.message}` }],
    }));
    return;
  }

  // Guard: the IR must carry node/flow arrays before any pass touches them.
  // A malformed IR (e.g. LLM returned partial JSON, or omitted a key) would
  // otherwise crash normalizeGateways with "Cannot read properties of
  // undefined (reading 'map')". Report it as a structured problem so the
  // repair loop can ask the LLM to regenerate rather than dying fatally.
  const shapeProblems = [];
  if (!ir || typeof ir !== 'object') {
    shapeProblems.push({ kind: 'parse', message: 'IR is not an object' });
  } else {
    if (!Array.isArray(ir.nodes)) {
      shapeProblems.push({ kind: 'parse', message: 'IR is missing a "nodes" array' });
    }
    if (!Array.isArray(ir.flows)) {
      shapeProblems.push({ kind: 'parse', message: 'IR is missing a "flows" array' });
    }
  }
  if (shapeProblems.length) {
    process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: shapeProblems }));
    return;
  }

  // Pass 1 — normalise (deterministic; no LLM involvement)
  const normIR = normalizeGateways(ir);

  // Guard: normalisation must eliminate all non-gateway fan-in / fan-out.
  // If any remain it is a pipeline bug — surface it so the repair loop handles it.
  const structProblems = assertNoImplicitSplitOrJoin(normIR);
  if (structProblems.length) {
    process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: structProblems, normalizedIR: normIR }));
    return;
  }

  // Pass 2 — pairing failures are structural; stop before compiling bad IR
  const pairingProblems = assertGatewayPairing(normIR);
  if (pairingProblems.length) {
    process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: pairingProblems, normalizedIR: normIR }));
    return;
  }

  // Lane structural checks — must pass before compilation so the repair loop
  // can ask the LLM to fix missing or invalid lane assignments.
  if (normIR.lanes && normIR.lanes.length) {
    const laneProblems = assertLaneAssignment(normIR);
    if (laneProblems.length) {
      process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: laneProblems, normalizedIR: normIR }));
      return;
    }
  }

  // Pass 3 — compile to BPMN XML + add layout DI
  let xml;
  try {
    xml = await compileIRtoBpmn(normIR);
    if (normIR.lanes && normIR.lanes.length) {
      // bpmn-auto-layout does not support Pools; generate DI manually.
      // buildManualLaneDI also validates Y-bounds and returns problems on failure.
      const { diSection, problems: diProblems } = buildManualLaneDI(normIR);
      if (diProblems.length) {
        process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: diProblems, normalizedIR: normIR }));
        return;
      }
      xml = injectLaneDI(xml, diSection);
    } else {
      xml = await addAutoLayout(xml);
    }
  } catch (err) {
    process.stdout.write(JSON.stringify({
      ok: false, xml: '',
      problems: [{ kind: 'compile', message: `Compile error: ${err.message}` }],
    }));
    return;
  }

  // Semantic validation is handled by the Python bpmn_validator layer after this step.
  // normalizedIR is returned so the repair loop can show the LLM the complete structure
  // (including compiler-inferred gateways) when asking for corrections.
  process.stdout.write(JSON.stringify({ ok: true, xml, problems: [], normalizedIR: normIR }));
}

main().catch(err => {
  process.stdout.write(JSON.stringify({
    ok: false, xml: '',
    problems: [{ kind: 'fatal', message: err.message }],
  }));
  process.exit(1);
});
