#!/usr/bin/env node
/**
 * BPMN IR → XML pipeline.
 *
 * Reads an IR JSON document from stdin, runs three deterministic passes:
 *   1. normalizeGateways   — eliminate task/event fan-out and fan-in
 *   2. assertGatewayPairing — reject mismatched opens/closes pairs before compiling
 *   3. compileIRtoBpmn     — build a bpmn-moddle tree, add DI layout
 *
 * For processes WITHOUT lanes: the same builder runs on one hidden lane, and the
 * frontend (spiff/src/utils/bpmnLayout.js) regenerates the layout on import.
 * For processes WITH lanes (pools): the manual builder lays out every lane; the
 * participant's process and drops the pool and lane bands entirely (still true
 * at 1.3.0, verified WI-002042), so BPMNDI is generated by buildManualLaneDI(),
 * which the frontend then keeps verbatim.
 *
 * buildManualLaneDI places one node per (lane, column) cell and routes every
 * edge through reserved gutters and strips on allocated channels, so no edge
 * enters a shape it does not connect to and no two shapes overlap. See the
 * comments on the routing model there, and one_bpmn/tests/test_lane_layout.py
 * for the guarantees that are pinned.
 *
 * Writes { ok, xml, problems:[{kind, message}] } to stdout.
 * Semantic validation is handled by the Python bpmn_validator layer.
 *
 * Invoked from bpmn_ir_pipeline.compile_ir() via subprocess.
 */

import { BpmnModdle } from 'bpmn-moddle';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { auditGeometry, boxesHit, segHitsBox } from './src/linting/geometry.js';

// ── Constants ─────────────────────────────────────────────────────────────────

const GATEWAY_TYPES = new Set([
  'exclusiveGateway', 'parallelGateway', 'inclusiveGateway',
]);

const BPMN_TYPE_MAP = {
  startEvent:       'bpmn:StartEvent',
  endEvent:         'bpmn:EndEvent',
  task:             'bpmn:ScriptTask',       // fallback; normalised IR should never emit bare task
  userTask:         'bpmn:UserTask',
  scriptTask:       'bpmn:ScriptTask',
  serviceTask:      'bpmn:ServiceTask',
  manualTask:       'bpmn:ManualTask',
  businessRuleTask: 'bpmn:BusinessRuleTask',
  exclusiveGateway: 'bpmn:ExclusiveGateway',
  parallelGateway:  'bpmn:ParallelGateway',
  inclusiveGateway: 'bpmn:InclusiveGateway',
  subProcess:       'bpmn:SubProcess',
};

// Layout constants for manual lane DI generation. Lane heights and column
// spacing are no longer fixed: buildManualLaneDI sizes each lane band and each
// column gutter to the routing channels it actually has to carry (WI-002042).
const PARTICIPANT_X    = 150;
const PARTICIPANT_Y    = 80;
const POOL_HEADER_W    = 30;   // vertical pool-name strip (leftmost)
const LANE_HEADER_W    = 30;   // per-lane name strip

// Per-type element dimensions (pixels)
const NODE_DIMS = {
  startEvent:       { w: 36, h: 36 },
  endEvent:         { w: 36, h: 36 },
  exclusiveGateway: { w: 50, h: 50 },
  parallelGateway:  { w: 50, h: 50 },
  inclusiveGateway: { w: 50, h: 50 },
};
const DEFAULT_NODE_DIMS = { w: 100, h: 80 };

function nodeDims(type) {
  return NODE_DIMS[type] || DEFAULT_NODE_DIMS;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function readStdin() {
  return new Promise((resolve, reject) => {
    let buf = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', chunk => { buf += chunk; });
    process.stdin.on('end',  () => resolve(buf));
    process.stdin.on('error', reject);
  });
}

function buildAdjacency(nodes, flows) {
  const out = new Map(nodes.map(n => [n.id, []]));
  const inn = new Map(nodes.map(n => [n.id, []]));
  for (const f of flows) {
    (out.get(f.from) || []).push(f);
    (inn.get(f.to)   || []).push(f);
  }
  return { out, inn };
}

let _seq = 0;
function uid(prefix) { return `${prefix}_${++_seq}`; }

// ── Pass 1: normalizeGateways ─────────────────────────────────────────────────
//
// Invariant enforced: no non-gateway node has >1 incoming or >1 outgoing flow.
//
//   no-implicit-split (task with >1 outgoing) → insert split gateway after node
//   fake-join         (task with >1 incoming) → insert join  gateway before node
//
// Inserted gateways are tagged { inferred: true } so downstream code can
// distinguish them from explicitly modelled gateways.

function normalizeGateways(ir) {
  let nodes = ir.nodes.map(n => ({ ...n }));
  let flows = ir.flows.map(f => ({ ...f }));

  // ── Fan-out pass ──
  {
    const { out } = buildAdjacency(nodes, flows);
    for (const n of [...nodes]) {
      if (GATEWAY_TYPES.has(n.type)) continue;
      const outFlows = out.get(n.id) || [];
      if (outFlows.length <= 1) continue;

      const gwType = outFlows.some(f => f.condition) ? 'exclusiveGateway' : 'parallelGateway';
      const gwId   = uid('gw_split');
      nodes.push({ id: gwId, type: gwType, name: `${n.name} Split`, inferred: true });

      // Repoint: all flows previously sourced from N now come from the new gateway
      flows = flows.map(f => outFlows.includes(f) ? { ...f, from: gwId } : f);
      // Bridge: N → gateway
      flows.push({ from: n.id, to: gwId });

      // Exclusive split must have exactly one default flow.
      // If all outgoing flows carry conditions (no obvious fallback), strip the last
      // one's condition and promote it to the unconditional default path.
      if (gwType === 'exclusiveGateway') {
        if (!flows.filter(f => f.from === gwId).some(f => f.default)) {
          let di = flows.findIndex(f => f.from === gwId && !f.condition && !f.default);
          const mustStrip = di < 0;
          if (di < 0) di = flows.reduce((best, f, i) => (f.from === gwId ? i : best), -1);
          if (di >= 0) {
            flows = flows.map((f, i) => {
              if (i !== di) return f;
              const f2 = { ...f, default: true };
              if (mustStrip) delete f2.condition;
              return f2;
            });
          }
        }
      }
    }
  }

  // ── Fan-in pass (rebuild adjacency after fan-out changes) ──
  {
    const { inn } = buildAdjacency(nodes, flows);
    for (const n of [...nodes]) {
      if (GATEWAY_TYPES.has(n.type)) continue;
      const inFlows = inn.get(n.id) || [];
      if (inFlows.length <= 1) continue;

      const gwId = uid('gw_join');
      nodes.push({ id: gwId, type: 'exclusiveGateway', name: `${n.name} Join`, inferred: true });

      // Repoint: all flows previously targeting N now target the join gateway
      flows = flows.map(f => inFlows.includes(f) ? { ...f, to: gwId } : f);
      // Bridge: join gateway → N
      flows.push({ from: gwId, to: n.id });
    }
  }

  // ── Gateway join-fork pass (rebuild adjacency after prior passes) ──
  // A gateway with >1 incoming AND >1 outgoing violates no-gateway-join-fork.
  // Fix: keep original as the join (N→1), insert a new fork gateway (1→N).
  {
    const { out, inn } = buildAdjacency(nodes, flows);
    for (const n of [...nodes]) {
      if (!GATEWAY_TYPES.has(n.type)) continue;
      const inFlows  = inn.get(n.id) || [];
      const outFlows = out.get(n.id) || [];
      if (inFlows.length <= 1 || outFlows.length <= 1) continue;

      // If none of the outgoing flows carry conditions or a default, the original gateway
      // had no routing logic — make the fork parallel so all paths run concurrently and
      // no conditional-flows check fires on the inferred fork.
      const forkType = outFlows.some(f => f.condition || f.default) ? n.type : 'parallelGateway';
      const forkId = uid('gw_fork');
      nodes.push({ id: forkId, type: forkType, name: `${n.name} Fork`, inferred: true });

      // All outgoing flows from original now come from the fork gateway
      flows = flows.map(f => outFlows.includes(f) ? { ...f, from: forkId } : f);
      // Bridge: join → fork
      flows.push({ from: n.id, to: forkId });

      // Exclusive fork must have exactly one default flow (same robust logic as fan-out pass).
      if (forkType === 'exclusiveGateway') {
        if (!flows.filter(f => f.from === forkId).some(f => f.default)) {
          let di = flows.findIndex(f => f.from === forkId && !f.condition && !f.default);
          const mustStrip = di < 0;
          if (di < 0) di = flows.reduce((best, f, i) => (f.from === forkId ? i : best), -1);
          if (di >= 0) {
            flows = flows.map((f, i) => {
              if (i !== di) return f;
              const f2 = { ...f, default: true };
              if (mustStrip) delete f2.condition;
              return f2;
            });
          }
        }
      }
    }
  }

  // ── Cleanup pass: remove superfluous gateways (1 in + 1 out) ──
  // normalizeGateways may insert join/fork gateways that end up unnecessary
  // when the IR structure doesn't actually require them (e.g. a join gateway
  // inserted for a node that only has one actual predecessor after other
  // normalization). Remove them and bridge predecessor → successor directly.
  {
    let changed = true;
    while (changed) {
      changed = false;
      const { out, inn } = buildAdjacency(nodes, flows);
      for (const n of [...nodes]) {
        if (!GATEWAY_TYPES.has(n.type)) continue;
        const inFlows  = inn.get(n.id) || [];
        const outFlows = out.get(n.id) || [];
        if (inFlows.length !== 1 || outFlows.length !== 1) continue;

        // This gateway is superfluous: exactly 1 in, 1 out
        const predFlow = inFlows[0];   // { from, to, ... }
        const succFlow = outFlows[0];  // { from, to, ... }

        // Bridge: predecessor → successor (preserve name/condition from the outgoing flow)
        const bridgeFlow = {
          from: predFlow.from,
          to:   succFlow.to,
          name: succFlow.name || predFlow.name || '',
        };
        if (succFlow.condition) bridgeFlow.condition = succFlow.condition;
        if (succFlow.default)   bridgeFlow.default   = succFlow.default;

        // Remove the two old flows and the gateway node
        flows = flows.filter(f => f !== predFlow && f !== succFlow);
        flows.push(bridgeFlow);
        nodes = nodes.filter(nd => nd.id !== n.id);
        changed = true;
        break;  // restart scan since adjacency changed
      }
    }
  }

  return { ...ir, nodes, flows };
}

// ── Post-normalization structural check ───────────────────────────────────────
//
// After all three normalizeGateways passes, every non-gateway node must have
// at most 1 outgoing and at most 1 incoming flow.  If any remain it means
// normalizeGateways has an unhandled edge case — surface it immediately so the
// Python repair loop can handle it rather than silently producing bad XML.

function assertNoImplicitSplitOrJoin(ir) {
  const problems = [];
  const { out, inn } = buildAdjacency(ir.nodes, ir.flows);
  for (const n of ir.nodes) {
    if (GATEWAY_TYPES.has(n.type)) continue;
    const outCount = (out.get(n.id) || []).length;
    const inCount  = (inn.get(n.id) || []).length;
    if (outCount > 1) {
      problems.push({
        kind: 'lint', rule: 'no-implicit-split', elementId: n.id,
        message: `Node "${n.id}" (${n.type}) still has ${outCount} outgoing flows after normalisation — normalizeGateways bug.`,
      });
    }
    if (inCount > 1) {
      problems.push({
        kind: 'lint', rule: 'fake-join', elementId: n.id,
        message: `Node "${n.id}" (${n.type}) still has ${inCount} incoming flows after normalisation — normalizeGateways bug.`,
      });
    }
  }
  return problems;
}

// ── Lane-assignment structural check ─────────────────────────────────────────
//
// When ir.lanes is present, every non-inferred node MUST declare a "lane" field
// whose value is a valid lane id.  Inferred gateways (inserted by normalizeGateways)
// are exempt — their lane is resolved later by propagation in buildManualLaneDI.
//
// Also checks that no sequence flow crosses pool boundaries (only relevant once
// multi-pool diagrams are supported; currently always satisfied, checked defensively).

function assertLaneAssignment(ir) {
  if (!ir.lanes || !ir.lanes.length) return [];
  const laneIds = new Set(ir.lanes.map(l => l.id));
  const problems = [];

  for (const n of ir.nodes) {
    if (n.inferred) continue;       // compiler-generated; lane set via propagation
    if (!n.lane) {
      problems.push({
        kind: 'structure', rule: 'lane-orphan', elementId: n.id,
        message: `Node "${n.id}" (${n.type}: "${n.name}") has no "lane" field. ` +
          `Every node must be assigned to a lane when lanes are defined. ` +
          `Valid lane ids: ${[...laneIds].join(', ')}.`,
      });
    } else if (!laneIds.has(n.lane)) {
      problems.push({
        kind: 'structure', rule: 'lane-orphan', elementId: n.id,
        message: `Node "${n.id}" (${n.type}: "${n.name}") references unknown lane "${n.lane}". ` +
          `Valid lane ids: ${[...laneIds].join(', ')}.`,
      });
    }
  }
  return problems;
}

// ── Pass 2: assertGatewayPairing ──────────────────────────────────────────────
//
// A node with `closes: "<splitId>"` declares it is the join counterpart of that
// split. The types must match: a parallelGateway split must be closed by a
// parallelGateway join. Mismatch passes bpmnlint but deadlocks Spiff at runtime.
// This pass rejects before compiling so the error reaches the LLM repair loop.

function assertGatewayPairing(ir) {
  const problems = [];
  const nodeMap  = new Map(ir.nodes.map(n => [n.id, n]));

  for (const n of ir.nodes) {
    if (!n.closes) continue;
    const split = nodeMap.get(n.closes);
    if (!split) {
      problems.push({
        kind:    'pairing',
        message: `Node "${n.id}" (${n.name}) declares closes="${n.closes}" but that node does not exist.`,
      });
    } else if (split.type !== n.type) {
      problems.push({
        kind:    'pairing',
        message:
          `Gateway pairing mismatch: "${n.id}" (type=${n.type}) closes "${split.id}" (type=${split.type}). ` +
          `A ${split.type} split must be closed by a ${split.type} join, not a ${n.type}.`,
      });
    }
  }

  return problems;
}

// ── Pass 3: compileIRtoBpmn ───────────────────────────────────────────────────
//
// Deterministic: same IR always produces the same moddle tree.
// Stable IDs are used as-is from the IR; flow IDs are derived from source+target+index.
// Incoming/outgoing refs and default pointers are wired exactly once.

async function compileIRtoBpmn(ir) {
  const moddle       = new BpmnModdle();
  const flowElements = [];
  const elementById  = new Map();

  // 1. Semantic nodes
  // Do NOT pass incoming/outgoing arrays — bpmn-moddle auto-wires them through the
  // sourceRef/targetRef inverse associations when it processes the Process flowElements.
  // Passing them AND manually pushing causes each flow to appear twice in the output.
  for (const n of ir.nodes) {
    const bpmnType = BPMN_TYPE_MAP[n.type] || 'bpmn:ScriptTask';
    const el = moddle.create(bpmnType, { id: n.id, name: n.name });
    elementById.set(n.id, el);
    flowElements.push(el);
  }

  // 2. Sequence flows — setting sourceRef/targetRef is sufficient; moddle wires
  // the inverse incoming/outgoing references automatically via its type descriptors.
  const seqMeta = [];
  for (let i = 0; i < ir.flows.length; i++) {
    const f   = ir.flows[i];
    const src = elementById.get(f.from);
    const tgt = elementById.get(f.to);
    if (!src || !tgt) continue;

    const sf = moddle.create('bpmn:SequenceFlow', {
      id:        `flow_${f.from}_${f.to}_${i}`,
      name:      f.name || '',
      sourceRef: src,
      targetRef: tgt,
    });

    if (f.condition) {
      sf.conditionExpression = moddle.create('bpmn:FormalExpression', { body: f.condition });
    }

    flowElements.push(sf);
    seqMeta.push({ sf, f });
  }

  // 3. Wire default flows on exclusive / inclusive gateways
  for (const { sf, f } of seqMeta) {
    if (f.default) {
      const src = elementById.get(f.from);
      if (src) src.default = sf;
    }
  }

  // 4. Lane set (optional) — lanes is [{ id, name, role? }]
  let laneSets;
  if (ir.lanes && ir.lanes.length) {
    const laneEls = ir.lanes.map(lane => {
      const flowNodeRef = (ir.nodes || [])
        .filter(n => n.lane === lane.id)
        .map(n => elementById.get(n.id))
        .filter(Boolean);
      return moddle.create('bpmn:Lane', { id: lane.id, name: lane.name, flowNodeRef });
    });
    laneSets = [moddle.create('bpmn:LaneSet', { id: 'LaneSet_1', lanes: laneEls })];
  }

  // 5. Process
  const processEl = moddle.create('bpmn:Process', {
    id:           'Process_1',
    isExecutable: true,
    flowElements,
    ...(laneSets ? { laneSets } : {}),
  });

  // 6. Collaboration + Participant (required for bpmn-js to render swim lanes)
  const rootElements = [processEl];
  if (laneSets) {
    const participantEl = moddle.create('bpmn:Participant', {
      id:         'Participant_1',
      name:       ir.name || 'Process',
      processRef: processEl,
    });
    const collaborationEl = moddle.create('bpmn:Collaboration', {
      id:           'Collaboration_1',
      participants: [participantEl],
    });
    rootElements.unshift(collaborationEl);  // collaboration must come first
  }

  const definitions = moddle.create('bpmn:Definitions', {
    id:              'Definitions_1',
    targetNamespace: 'http://bpmn.io/schema/bpmn',
    exporter:        'processa-pipeline',
    exporterVersion: '1.0',
    rootElements,
  });

  const { xml } = await moddle.toXML(definitions, { format: true });
  return xml;
}

// ── Manual DI builder for lane-based processes ────────────────────────────────
//
// Every diagram is laid out here. bpmn-auto-layout used to take lane-less IR and
// put 59 crossings on a 47-node map; a hidden single lane on this grid does better.
//
// Algorithm:
//   1. Propagate lane assignments to inferred gateways (no explicit lane field)
//   2. Topological column assignment: longest-path BFS so elements flow left→right
//   3. Within each (lane, column) cell, stack elements vertically
//   4. Emit BPMNDiagram XML: participant → lanes → node shapes → edge waypoints

function buildManualLaneDI(ir, opts = {}) {
  const pool  = opts.pool !== false;   // false: lane-less diagram laid out on one hidden lane
  const lanes = ir.lanes || [];   // [{ id, name, role? }]
  if (!lanes.length) return '';

  const laneIndexById = new Map(lanes.map((l, i) => [l.id, i]));
  const nodeMap       = new Map(ir.nodes.map(n => [n.id, n]));

  // Build adjacency for lane propagation and column assignment
  const adjOut = new Map(ir.nodes.map(n => [n.id, []]));
  const adjInn = new Map(ir.nodes.map(n => [n.id, []]));
  for (const f of ir.flows) {
    if (adjOut.has(f.from)) adjOut.get(f.from).push(f.to);
    if (adjInn.has(f.to))   adjInn.get(f.to).push(f.from);
  }

  // Propagate lane id to inferred gateways (no explicit lane field).
  // Iterates until stable so multi-hop chains resolve correctly.
  const nodeLaneId = new Map();
  for (const n of ir.nodes) {
    if (n.lane) nodeLaneId.set(n.id, n.lane);
  }
  let changed = true;
  while (changed) {
    changed = false;
    for (const n of ir.nodes) {
      if (nodeLaneId.has(n.id)) continue;
      const neighbours = (adjInn.get(n.id) || []).concat(adjOut.get(n.id) || []);
      for (const nb of neighbours) {
        if (nodeLaneId.has(nb)) {
          nodeLaneId.set(n.id, nodeLaneId.get(nb));
          changed = true;
          break;
        }
      }
    }
  }
  // Final fallback: unresolved nodes go to first lane
  for (const n of ir.nodes) {
    if (!nodeLaneId.has(n.id) && lanes.length) nodeLaneId.set(n.id, lanes[0].id);
  }

  // ── Back-edge detection via iterative DFS from start ─────────────────────
  // Kahn's topological sort fails on cyclic flows (loops, re-check paths).
  // We detect back edges first so the column assignment treats the process as a
  // DAG, placing nodes in a proper left-to-right sequence.  Back edges are still
  // drawn as arrows; they just arc back to an earlier column.
  const startNodeId = (ir.nodes.find(n => n.type === 'startEvent') || ir.nodes[0] || {}).id;
  const backEdges   = new Set();  // "from:to" key strings

  if (startNodeId) {
    const dfsVisited = new Set([startNodeId]);
    const dfsInStack = new Set([startNodeId]);
    // Each frame: [nodeId, nextChildIndex]
    const dfsStack   = [[startNodeId, 0]];

    while (dfsStack.length) {
      const frame    = dfsStack[dfsStack.length - 1];
      const nodeId   = frame[0];
      const children = adjOut.get(nodeId) || [];

      if (frame[1] >= children.length) {
        dfsInStack.delete(nodeId);
        dfsStack.pop();
      } else {
        const nextId = children[frame[1]++];
        if (dfsInStack.has(nextId)) {
          backEdges.add(nodeId + ':' + nextId);   // cycle → back edge
        } else if (!dfsVisited.has(nextId)) {
          dfsVisited.add(nextId);
          dfsInStack.add(nextId);
          dfsStack.push([nextId, 0]);
        }
      }
    }
  }

  // ── Column assignment: one node per (lane, column) cell ──────────────────
  //
  // Walk the DAG in topological order (back edges excluded) and place each node
  // in the first FREE cell at or after max(predecessor column) + 1.
  //
  // The previous version was a plain longest-path DP, which let any number of
  // nodes share a cell and then squeezed them into the lane band by dividing its
  // height between them. On a real map that is ruinous: 46 nodes over 9 columns
  // put fifteen nodes in one cell, so the band stretched to ~1700px, every edge
  // needed long vertical travel, and shapes were metres apart from the lane they
  // belonged to. Reserving a cell per node keeps the diagram a left-to-right
  // flow — which is also what makes "no shape overlaps another shape" true by
  // construction rather than by validation.
  //
  // Nodes in DIFFERENT lanes still share a column: that is genuine concurrency
  // and reads correctly.
  const laneIdxOf = (id) => {
    const lid = nodeLaneId.get(id) || lanes[0].id;
    return laneIndexById.has(lid) ? laneIndexById.get(lid) : 0;
  };

  const inDeg = new Map(ir.nodes.map(n => [n.id, 0]));
  for (const f of ir.flows) {
    if (backEdges.has(f.from + ':' + f.to)) continue;   // skip back edges
    if (inDeg.has(f.to)) inDeg.set(f.to, (inDeg.get(f.to) || 0) + 1);
  }
  const queue = ir.nodes.filter(n => inDeg.get(n.id) === 0).map(n => n.id);
  const ordered = [];
  const seen = new Set(queue);
  let qi = 0;
  while (qi < queue.length) {
    const id = queue[qi++];
    ordered.push(id);
    for (const succId of (adjOut.get(id) || [])) {
      if (backEdges.has(id + ':' + succId)) continue;
      const deg = (inDeg.get(succId) || 1) - 1;
      inDeg.set(succId, deg);
      if (deg === 0 && !seen.has(succId)) { seen.add(succId); queue.push(succId); }
    }
  }
  // Anything the walk never reached (a cycle with no acyclic entry point) still
  // has to be placed, or it would silently pile up in column 0.
  for (const n of ir.nodes) if (!seen.has(n.id)) ordered.push(n.id);

  // Parallel branches of one fork are SIBLINGS: they share a predecessor and
  // belong side by side in the same column, one per row, the way a diamond is
  // drawn. Without this a two-way split inside one lane was laid out in series
  // (g → a → b → join), and the two branch flows had to detour around the node
  // each did not touch — detours that crossed by construction. Unrelated nodes
  // still get their own column, so a wide map cannot collapse into one cell.
  const MAX_ROWS = 3;
  const forwardPreds = (id) => (adjInn.get(id) || []).filter(p => !backEdges.has(p + ':' + id));
  const col   = new Map();
  const cells = new Map();   // "laneIdx:col" → nodeIds placed there, one per row
  for (const id of ordered) {
    let c = 0;
    for (const predId of forwardPreds(id)) {
      if (col.has(predId)) c = Math.max(c, col.get(predId) + 1);
    }
    const li = laneIdxOf(id);
    const preds = new Set(forwardPreds(id));
    const isSibling = (other) => forwardPreds(other).some(p => preds.has(p));
    for (;;) {
      const here = cells.get(li + ':' + c) || [];
      if (!here.length) break;
      if (here.length < MAX_ROWS && here.every(isSibling)) break;
      c++;
    }
    const key = li + ':' + c;
    if (!cells.has(key)) cells.set(key, []);
    cells.get(key).push(id);
    col.set(id, c);
  }
  for (const n of ir.nodes) { if (!col.has(n.id)) col.set(n.id, 0); }

  const maxCol = ir.nodes.reduce((m, n) => Math.max(m, col.get(n.id) || 0), 0);

  // Group nodes by (laneIdx, col) cell for vertical stacking
  const groups = new Map();  // key "li:c" → { li, c, nodeIds[] }
  for (const n of ir.nodes) {
    const lid = nodeLaneId.get(n.id) || lanes[0].id;
    const li  = laneIndexById.has(lid) ? laneIndexById.get(lid) : 0;
    const c   = col.get(n.id) || 0;
    const k   = li + ':' + c;
    if (!groups.has(k)) groups.set(k, { li, c, nodeIds: [] });
    groups.get(k).nodeIds.push(n.id);
  }

  // ── Channel routing model (WI-002042) ────────────────────────────────────
  //
  // Nodes sit on a (lane, column, row) grid. The space BETWEEN those cells is
  // reserved and never occupied by a shape: a vertical GUTTER between adjacent
  // columns, and a horizontal STRIP along the bottom of each lane. Every pixel
  // of edge travel happens inside one of them, so an edge can never cross a
  // shape it does not connect to.
  //
  // Two edges sharing a gutter or strip are given different CHANNELS, so they
  // never render as one line. Channels are allocated by occupancy — greedy
  // interval colouring over the ordinal grid — not by the flow's array index.
  // The previous generator offset overlapping edges by `(i % 3) * 10`, giving
  // three channels 10px apart chosen by position in the array, which is why
  // return edges piled onto each other and onto the lane's own node rows.
  //
  // Allocation runs on ORDINAL coordinates (row ordinals, column indices),
  // which are monotonic in pixels, so the channel counts are known before any
  // pixel is computed and the whole layout resolves in a single pass.
  const CH_SP        = 14;   // gap between neighbouring channels in a gutter/strip
  const GUTTER_BASE  = 70;   // clear space between node columns before channels
  const ROW_PITCH    = 110;  // vertical pitch of node rows inside a lane
  const ROW_BAND     = 80;   // tallest node; rows share this centreline
  const LANE_PAD_TOP = 28;
  const LANE_PAD_BOT = 16;
  const STRIP_BASE   = 28;   // clear space in a lane's routing strip

  // Row index of each node within its (lane, column) cell.
  const rowOf = new Map();
  for (const grp of groups.values()) grp.nodeIds.forEach((id, r) => rowOf.set(id, r));

  const laneRows = lanes.map((_, li) => {
    let m = 1;
    for (const g of groups.values()) if (g.li === li) m = Math.max(m, g.nodeIds.length);
    return m;
  });

  // Column width is the widest node in that column, so every column is a clean
  // vertical band and the gutters either side of it stay shape-free.
  const colW = [];
  for (let c = 0; c <= maxCol; c++) colW[c] = 36;
  for (const n of ir.nodes) {
    const c = col.get(n.id) || 0;
    colW[c] = Math.max(colW[c], nodeDims(n.type).w);
  }

  // Ordinal vertical axis: every lane contributes its node rows plus one slot
  // for its routing strip, so ordinals increase monotonically down the pool.
  //
  // Each lane reserves a routing strip on BOTH sides of its node rows, not just
  // below them. A lane only ever had a strip underneath, so a return loop was
  // forced into the band that every downward edge in that lane has to cross on
  // its way to the lane below — the loop and the branch that left for the next
  // lane crossed by construction, and no channel allocation could help, because
  // the two are perpendicular. Given the choice, a loop takes the side with less
  // vertical traffic through it, which for a lane's own rework loop is normally
  // the top: nothing passes overhead in the first lane at all.
  const laneRowOffset = [];
  let ordAcc = 0;
  for (let li = 0; li < lanes.length; li++) { laneRowOffset.push(ordAcc); ordAcc += laneRows[li] + 2; }
  const ordOf       = (li, row) => laneRowOffset[li] + 1 + row;
  const ordTop      = (li)      => laneRowOffset[li];
  const ordBottom   = (li)      => laneRowOffset[li] + 1 + laneRows[li];
  const stripKey    = (li, side) => li * 2 + (side === 'top' ? 0 : 1);
  const ordStripFor = (li, side) => (side === 'top' ? ordTop(li) : ordBottom(li));

  const occupied = new Set();
  for (const grp of groups.values()) {
    grp.nodeIds.forEach((id, r) => occupied.add(grp.li + ':' + grp.c + ':' + r));
  }
  // Can an edge run straight along this row between these columns?
  const rowClear = (li, row, cFrom, cTo) => {
    for (let c = cFrom; c <= cTo; c++) if (occupied.has(li + ':' + c + ':' + row)) return false;
    return true;
  };

  // Which nodes sit in each column, by vertical ordinal — for the safety check.
  const colCells = new Map();
  for (const grp of groups.values()) {
    if (!colCells.has(grp.c)) colCells.set(grp.c, []);
    grp.nodeIds.forEach((id, r) => colCells.get(grp.c).push({ id, ord: ordOf(grp.li, r) }));
  }
  // Is column `c` free of nodes strictly between these two ordinals?
  const colClearBetween = (c, oA, oB, skip) => {
    const lo = Math.min(oA, oB), hi = Math.max(oA, oB);
    for (const cell of colCells.get(c) || []) {
      if (skip.has(cell.id)) continue;
      if (cell.ord > lo && cell.ord < hi) return false;
    }
    return true;
  };

  // How much vertical traffic passes through a horizontal band?
  //
  // Any flow whose ends sit on different ordinals must travel vertically
  // somewhere between its two columns, so it crosses every band strictly
  // between them. That is known from the grid alone, before a single route is
  // chosen, which is what lets a strip pick its side up front instead of
  // discovering the collision after the fact.
  const travel = [];
  for (const f of ir.flows) {
    if (!nodeMap.has(f.from) || !nodeMap.has(f.to)) continue;
    const a = ordOf(laneIdxOf(f.from), rowOf.get(f.from) || 0);
    const b = ordOf(laneIdxOf(f.to), rowOf.get(f.to) || 0);
    if (a === b) continue;
    const ca = col.get(f.from) || 0, cb = col.get(f.to) || 0;
    travel.push({
      oLo: Math.min(a, b), oHi: Math.max(a, b),
      cLo: Math.min(ca, cb), cHi: Math.max(ca, cb),
    });
  }
  const trafficThrough = (ord, cLo, cHi) => {
    let n = 0;
    for (const t of travel) {
      if (t.oLo < ord && ord < t.oHi && t.cLo <= cHi && cLo <= t.cHi) n++;
    }
    return n;
  };

  // ── Plan every edge on the grid, before any pixel exists ──────────────────
  const vRuns = [];   // vertical runs, keyed by gutter index
  const hRuns = [];   // horizontal runs, keyed by lane index and side (its strips)
  const cRuns = [];   // vertical runs travelling inside a node column, keyed by column
  // A docked or face-exiting edge runs its vertical leg inside a node's own
  // column rather than in a gutter, so those legs need allocating too — two of
  // them in one column with overlapping spans are two lines on one pixel, which
  // is the same defect the gutters were built to remove. Spreading them per node
  // is not enough: the collision is between edges at DIFFERENT nodes of the same
  // column, which no per-node fan can see.
  const colRun = (p, c, oA, oB) => {
    p.cvCol = c;
    p.cv = { key: c, lo: Math.min(oA, oB), hi: Math.max(oA, oB) };
    cRuns.push(p.cv);
  };
  const plans = [];
  //
  // The APPROACH is decided here too, not in a later pass, because a docked
  // route travels different corridors from the one the planner would otherwise
  // have given it — deciding afterwards reserved channels the edge then never
  // used, and left the segments it did use outside the allocation entirely.
  for (const f of ir.flows) {
    if (!nodeMap.has(f.from) || !nodeMap.has(f.to)) { plans.push(null); continue; }
    const sl = laneIdxOf(f.from), tl = laneIdxOf(f.to);
    const sc = col.get(f.from) || 0, tc = col.get(f.to) || 0;
    const sr = rowOf.get(f.from) || 0, tr = rowOf.get(f.to) || 0;
    const p = { f, sl, tl, sc, tc, sr, tr };
    const so = ordOf(sl, sr), to = ordOf(tl, tr);
    const ends = new Set([f.from, f.to]);

    if (tc > sc && sl === tl && sr === tr && rowClear(tl, tr, sc + 1, tc - 1)) {
      // Same row, nothing in the way — the plain left-to-right arrow.
      p.kind = 'straight';
    } else if (tc > sc && so !== to
               && rowClear(sl, sr, sc + 1, tc)
               && colClearBetween(tc, so, to, ends)) {
      // Target-side dock: out along the source's own row, then down (or up) the
      // target's own column into its top or bottom edge. One bend, no arrival
      // stub, and no corridor used at all.
      p.kind = 'dock';
      p.dock = to > so ? 'top' : 'bottom';
      colRun(p, tc, so, to);
    } else if (tc > sc && so !== to
               && colClearBetween(sc, so, to, ends)
               && rowClear(tl, tr, sc, tc - 1)) {
      // Source-side exit — the mirror image, and the case the target-side dock
      // cannot serve: the source's row is blocked (a sibling branch occupies the
      // column the edge would have crossed) but the source's OWN column is free
      // and the target's row is clear. Leaving through the source's bottom (or
      // top) face drops the edge out of that traffic immediately, instead of
      // pushing a stub out to the right past every sibling that leaves with it.
      //
      // This is the shape of a gateway with one branch continuing in its lane
      // and another dropping to the lane below: routed to the right, the drop
      // always crosses the branch that carried straight on.
      p.kind = 'vexit';
      p.exitFace = to > so ? 'bottom' : 'top';
      colRun(p, sc, so, to);
    } else if (tc > sc && (tc === sc + 1 || rowClear(tl, tr, sc + 1, tc - 1))) {
      // Forward hop: drop through the gutter immediately right of the source,
      // then run in along the target's own row, which we know is clear.
      p.kind = 'elbow';
      p.g1 = sc;
      p.v1 = {
        key: sc,
        lo: Math.min(ordOf(sl, sr), ordOf(tl, tr)),
        hi: Math.max(ordOf(sl, sr), ordOf(tl, tr)),
      };
      vRuns.push(p.v1);
    } else {
      // Blocked forward hop, or a back edge. Travel horizontally in a routing
      // strip rather than across the diagram body: the target's own strip going
      // forward, and for a back edge the strip of the LOWER of the two lanes, so
      // a loop inside one lane stays inside that lane instead of arcing over the
      // whole pool.
      p.kind = 'strip';
      // The TARGET lane's strips, forwards and backwards alike: the edge then
      // makes its long horizontal run in the band it is already heading for and
      // arrives with a short vertical. Measured against the alternatives on the
      // Fuel Requisition map (avoidable crossings): target lane 228, source lane
      // 285, lower of the two 287, one shared bus below the pool 392 — a shared
      // bus is worst because every lane-changing edge in the diagram then has to
      // cross it.
      p.rl = tl;
      p.g1 = sc;
      p.g2 = tc - 1;
      // Pick the side of the lane with less vertical traffic crossing the span
      // this edge has to cover. Ties go to the bottom, which is the side a
      // reader expects a return loop on when neither is busier.
      const span = { lo: Math.min(sc, tc), hi: Math.max(sc, tc) };
      const topCost = trafficThrough(ordTop(p.rl), span.lo, span.hi);
      const botCost = trafficThrough(ordBottom(p.rl), span.lo, span.hi);
      p.side = topCost < botCost ? 'top' : 'bottom';
      const sto = ordStripFor(p.rl, p.side);
      // Source-side exit onto the strip, the mirror of the dock below: if the
      // source's own column is clear down (or up) to the strip, the edge drops
      // straight out of its bottom face instead of stubbing right to a gutter.
      // That stub is what crossed the source's OTHER outgoing flow — the normal
      // continuation leaving the same node — on every rework loop we have drawn.
      if (colClearBetween(sc, ordOf(sl, sr), sto, ends)) {
        p.exitFace = sto > ordOf(sl, sr) ? 'bottom' : 'top';
        p.g1 = sc;   // the strip run starts at the source's own column
        colRun(p, sc, ordOf(sl, sr), sto);
      } else {
        p.v1 = { key: p.g1, lo: Math.min(ordOf(sl, sr), sto), hi: Math.max(ordOf(sl, sr), sto) };
        vRuns.push(p.v1);
      }
      // A strip runs clear of every node row in its lane, so an edge riding one
      // can finish by turning into the target's near face instead of out to a
      // gutter and back in along the target's row. That is the return-loop shape:
      // the leg that used to come up a gutter one column short of the target and
      // run in sideways is exactly the leg that crossed whatever else entered
      // that target. Back edges were excluded from docking before, which is why
      // a rework loop always crossed the flow it was rejoining.
      if (colClearBetween(tc, ordOf(tl, tr), sto, ends)) {
        p.dock = p.side === 'top' ? 'top' : 'bottom';
        p.dockRun = { key: tc, lo: Math.min(ordOf(tl, tr), sto), hi: Math.max(ordOf(tl, tr), sto) };
        cRuns.push(p.dockRun);
        p.h1 = { key: stripKey(p.rl, p.side), lo: Math.min(p.g1, tc), hi: Math.max(p.g1, tc) };
      } else {
        p.v2 = { key: p.g2, lo: Math.min(ordOf(tl, tr), sto), hi: Math.max(ordOf(tl, tr), sto) };
        p.h1 = { key: stripKey(p.rl, p.side), lo: Math.min(p.g1, p.g2), hi: Math.max(p.g1, p.g2) };
        vRuns.push(p.v2);
      }
      hRuns.push(p.h1);
    }
    plans.push(p);
  }

  // Channel allocation by interval NESTING, then first fit.
  //
  // Runs are sorted narrowest-first, so a run always lands on a channel at or
  // below any run that contains it. That ordering is what actually removes
  // crossings: if run A's span is nested inside run B's, A only ever travels out
  // to its own channel, which is nearer the nodes than B's, so A's two vertical
  // legs stop short of B's horizontal and the two never meet. Only genuinely
  // interleaved spans — the ones no planar drawing can separate either — are
  // left crossing.
  //
  // Sorting by position instead (the obvious first-fit) packs channels just as
  // tightly but shuffles nested runs above their containers, which manufactures
  // crossings that the geometry did not require: it cost ~460 avoidable
  // crossings on the Fuel Requisition map.
  //
  // Within a channel, runs that do not overlap at all still share it, so the
  // gutter or strip stays as narrow as the traffic allows.
  const allocate = (runs) => {
    const byKey = new Map();
    for (const r of runs) {
      if (!byKey.has(r.key)) byKey.set(r.key, []);
      byKey.get(r.key).push(r);
    }
    const counts = new Map();
    for (const [k, list] of byKey) {
      list.sort((a, b) => (a.hi - a.lo) - (b.hi - b.lo) || a.lo - b.lo);
      const channels = [];   // channels[i] = intervals already placed there
      for (const r of list) {
        let i = 0;
        for (; i < channels.length; i++) {
          if (!channels[i].some(o => o.lo < r.hi && r.lo < o.hi)) break;
        }
        if (i === channels.length) channels.push([]);
        channels[i].push(r);
        r.ch = i;
      }
      counts.set(k, channels.length);
    }
    return counts;
  };
  const gutterCount = allocate(vRuns);
  const colVCount   = allocate(cRuns);
  const stripCount  = allocate(hRuns);

  // ── Pixels: gutters and strips are sized to the channels they must hold ───
  const gutterW = (g)  => Math.max(GUTTER_BASE, 40 + (gutterCount.get(g) || 0) * CH_SP);
  const stripH  = (li, side) => {
    const n = stripCount.get(stripKey(li, side)) || 0;
    return n ? Math.max(STRIP_BASE, 14 + n * CH_SP) : (side === 'top' ? 0 : STRIP_BASE);
  };

  const contentLeft = PARTICIPANT_X + POOL_HEADER_W + LANE_HEADER_W;
  const colLeft = [];
  let penX = contentLeft + gutterW(-1);
  for (let c = 0; c <= maxCol; c++) { colLeft[c] = penX; penX += colW[c] + gutterW(c); }

  const gutterStart = (g) => (g < 0 ? contentLeft : colLeft[g] + colW[g]);
  const gutterX = (g, ch) => Math.round(gutterStart(g) + 20 + ch * CH_SP);

  const laneH = lanes.map((_, li) =>
    LANE_PAD_TOP + stripH(li, 'top') + laneRows[li] * ROW_PITCH + stripH(li, 'bottom') + LANE_PAD_BOT);
  const laneTopY = [];
  let yOff = PARTICIPANT_Y;
  for (let i = 0; i < lanes.length; i++) { laneTopY.push(yOff); yOff += laneH[i]; }
  const totalH       = yOff - PARTICIPANT_Y;
  const participantW = penX - PARTICIPANT_X;

  const rowCenterY = (li, row) =>
    laneTopY[li] + LANE_PAD_TOP + stripH(li, 'top') + row * ROW_PITCH + ROW_BAND / 2;
  // Channel 0 is always the one NEAREST the node rows, on both sides. Channel
  // allocation sorts runs narrowest-first precisely so a nested run sits inside
  // its container, and "inside" means closer to the nodes — so on a top strip
  // the channels have to count upwards from the rows, not downwards from the
  // lane's edge. Numbering it the other way inverts every nesting relationship
  // in that strip and manufactures exactly the crossings the sort prevents.
  const stripY = (li, side, ch) => Math.round(
    side === 'top'
      ? laneTopY[li] + LANE_PAD_TOP + stripH(li, 'top') - 8 - ch * CH_SP
      : laneTopY[li] + LANE_PAD_TOP + stripH(li, 'top') + laneRows[li] * ROW_PITCH + 14 + ch * CH_SP);

  // Every node centred in its column and on its row's centreline: rows cannot
  // overlap (ROW_PITCH exceeds the tallest node) and columns cannot either.
  const nodePos = new Map();  // nodeId → { x, y, w, h }
  for (const grp of groups.values()) {
    grp.nodeIds.forEach((nid, r) => {
      const d = nodeDims(nodeMap.get(nid).type);
      nodePos.set(nid, {
        x: Math.round(colLeft[grp.c] + (colW[grp.c] - d.w) / 2),
        y: Math.round(rowCenterY(grp.li, r) - d.h / 2),
        w: d.w,
        h: d.h,
      });
    });
  }

  // ── Y-bounds validation ───────────────────────────────────────────────────────
  // Every node's rendered shape must fall inside its assigned lane band.
  // By construction our layout algorithm guarantees this; the check acts as a
  // safety net that catches wrong lane assignments or future layout-algorithm bugs.
  const boundProblems = [];
  for (const n of ir.nodes) {
    const pos = nodePos.get(n.id);
    if (!pos) continue;
    const lid = nodeLaneId.get(n.id) || (lanes.length ? lanes[0].id : '');
    const li  = laneIndexById.has(lid) ? laneIndexById.get(lid) : 0;
    const bandTop    = laneTopY[li];
    const bandBottom = bandTop + laneH[li];
    if (pos.y < bandTop - 1 || pos.y + pos.h > bandBottom + 1) {
      boundProblems.push({
        kind: 'structure', rule: 'lane-bounds', elementId: n.id,
        message: `Node "${n.id}" Y-bounds [${pos.y}–${pos.y + pos.h}] fall outside ` +
          `lane "${lid}" band [${bandTop}–${bandBottom}]. ` +
          `Change this node's "lane" field to the correct lane id.`,
      });
    }
  }
  if (boundProblems.length) return { diSection: '', problems: boundProblems };

  // ── Serialise BPMNDI XML ──────────────────────────────────────────────────────
  const lines = [];
  lines.push('  <bpmndi:BPMNDiagram id="BPMNDiagram_1">');
  lines.push('    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="' + (pool ? 'Collaboration_1' : 'Process_1') + '">');

  if (pool) {
  // Participant (pool) shape
  lines.push('      <bpmndi:BPMNShape id="Participant_1_di" bpmnElement="Participant_1" isHorizontal="true">');
  lines.push('        <dc:Bounds x="' + PARTICIPANT_X + '" y="' + PARTICIPANT_Y +
             '" width="' + participantW + '" height="' + totalH + '" />');
  lines.push('      </bpmndi:BPMNShape>');
  }

  // Lane shapes — bands tile exactly (heights sum to pool inner height)
  for (let i = 0; pool && i < lanes.length; i++) {
    const lane = lanes[i];
    const laneX = PARTICIPANT_X + POOL_HEADER_W;
    const laneW = participantW - POOL_HEADER_W;
    lines.push('      <bpmndi:BPMNShape id="' + lane.id + '_di" bpmnElement="' + lane.id + '" isHorizontal="true">');
    lines.push('        <dc:Bounds x="' + laneX + '" y="' + laneTopY[i] +
               '" width="' + laneW + '" height="' + laneH[i] + '" />');
    lines.push('      </bpmndi:BPMNShape>');
  }

  // Node shapes are serialised after the edges (below): an event or gateway
  // label has to know where every line runs before it can pick a clear side.
  const edgeLines = [];
  const allSegs = [];       // [p, q, flowIndex]
  const edgePts = [];

  // Label collision test: an edge label must not land on another label, nor on
  // a shape it has nothing to do with. Seeded with every node shape so the very
  // first label already avoids them.
  const labelBoxes = [];
  const boxHit = (a, b) =>
    a.x < b.x + b.w && b.x < a.x + a.w && a.y < b.y + b.h && b.y < a.y + a.h;

  // ── Docking: choose which SIDE of a node each edge attaches to ────────────
  //
  // The channel model already keeps corridors apart — measured on these maps
  // only 3 of 69 overlapping segment pairs were in a gutter or a strip. The
  // other 66 were the short horizontal STUBS at the nodes: the run from a
  // shape's right edge out to the gutter, and from the last gutter back in to
  // the target's left edge.
  //
  // Those stubs were collinear BY CONSTRUCTION. Every edge left at (x+w, y+h/2)
  // and arrived at (x, y+h/2), so seven flows converging on one join gateway
  // began as seven lines on the same pixel row, differing only in where they
  // turned. No corridor allocation can separate them, because the collision is
  // at the endpoint. And spreading them along the edge does not rescue it
  // either: a gateway is 50px tall, so seven arrivals cannot be 12px apart.
  //
  // So an edge that approaches VERTICALLY docks on the target's top or bottom
  // edge instead, running its last leg down the target's own column. That
  // removes the stub rather than shortening it, and costs a corner rather than
  // adding one: the route becomes exit-row -> vertical -> dock, one bend where
  // the gutter route needed two (or four via a strip).
  //
  // It is only allowed when provably safe. The column is normally reserved for
  // shapes, so the vertical may only run there when no other node sits in that
  // column between the two rows, and the horizontal that reaches it must cross
  // a clear row. Where either fails, the edge keeps the old gutter/strip route
  // and instead gets a distributed attachment on the left edge.
  const DOCK_INSET = 9;   // keep a dock this far inside the node's corner


  // ── Spread the attachment points that remain ──────────────────────────────
  // Docked edges share the target's top or bottom edge, so they are spread along
  // its WIDTH; the rest share its left edge and are spread along its HEIGHT.
  // Either way each edge gets its own line, and the fan is ordered by where the
  // edge comes from so it cannot cross itself.
  const exitY = new Map(), entryY = new Map();

  const farEndY = (p) => rowCenterY(p.tl, p.tr);   // where an outgoing edge is headed
  const nearEndY = (p) => rowCenterY(p.sl, p.sr);  // where an incoming edge came from

  // Slots are laid on a fixed pitch and any slot too near a pinned one is
  // discarded, rather than dividing the edge evenly among the movers. Dividing
  // evenly looks right and is wrong: with one pinned straight edge and one other
  // arrival, the mover's single slot lands at the midpoint — which IS the
  // centreline the straight edge is pinned to — so the two arrive on the same
  // pixel and read as one line. That was 2 of the 7 overlaps on a 14-edge
  // fixture, and it is the commonest shape there is: a task with one normal
  // predecessor and one rework loop.
  const SLOT_PITCH = 13;

  const fan = (idxs, lo, hi, keyOf, store, pinned, pinAt) => {
    for (const i of pinned) store.set(i, pinAt);
    const items = idxs.filter(i => !pinned.has(i));
    if (!items.length) return;
    items.sort((a, b) => keyOf(plans[a]) - keyOf(plans[b]));

    const slots = [];
    for (let y = lo; y <= hi; y += SLOT_PITCH) {
      if (pinned.size && Math.abs(y - pinAt) < SLOT_PITCH) continue;
      slots.push(y);
    }
    if (!slots.length) slots.push(Math.round((lo + hi) / 2));

    // Spread the movers across whatever slots survived, keeping their order.
    items.forEach((i, k) => {
      const at = items.length === 1
        ? slots[Math.floor(slots.length / 2)]
        : slots[Math.round((k * (slots.length - 1)) / (items.length - 1))];
      store.set(i, Math.round(at));
    });
  };

  const outOf = new Map(), into = new Map();
  for (let i = 0; i < plans.length; i++) {
    const p = plans[i];
    if (!p) continue;
    if (!outOf.has(p.f.from)) outOf.set(p.f.from, []);
    if (!into.has(p.f.to)) into.set(p.f.to, []);
    outOf.get(p.f.from).push(i);
    into.get(p.f.to).push(i);
  }

  // Exits: every outgoing edge leaves the right edge, so they fan over its height.
  // A straight edge is pinned to the centreline — moving it would turn a
  // two-point line into a four-point one.
  for (const [nid, idxs] of outOf) {
    const pos = nodePos.get(nid);
    if (!pos) continue;
    // Edges leaving through a horizontal face have their x fixed by the column
    // allocation above, which sees the whole column rather than this one node;
    // only the ones still leaving the right edge need fanning over its height.
    const onRight = idxs.filter(i => plans[i] && !plans[i].exitFace);
    const pinned = new Set(onRight.filter(i => plans[i] && plans[i].kind === 'straight'));
    fan(onRight, pos.y + DOCK_INSET, pos.y + pos.h - DOCK_INSET, farEndY, exitY,
        pinned, Math.round(pos.y + pos.h / 2));
  }

  // Arrivals: split by the side each one docks on.
  for (const [nid, idxs] of into) {
    const pos = nodePos.get(nid);
    if (!pos) continue;
    const straight = new Set(idxs.filter(i => plans[i] && plans[i].kind === 'straight'));
    const onLeft = idxs.filter(i => plans[i] && !plans[i].dock);
    fan(onLeft, pos.y + DOCK_INSET, pos.y + pos.h - DOCK_INSET, nearEndY, entryY,
        straight, Math.round(pos.y + pos.h / 2));
  }

  // ── Sequence-flow edges ───────────────────────────────────────────────────
  // Every segment rides a channel allocated above, so no segment can enter a
  // shape it does not connect to and no two segments can share a line.
  for (let i = 0; i < ir.flows.length; i++) {
    const p = plans[i];
    if (!p) continue;
    const f   = p.f;
    const src = nodePos.get(f.from);
    const tgt = nodePos.get(f.to);
    if (!src || !tgt) continue;

    // Always leave the right edge and arrive at the left edge: the direction of
    // travel then reads consistently everywhere on the canvas.
    const sx = src.x + src.w;
    const sy = exitY.has(i) ? exitY.get(i) : Math.round(src.y + src.h / 2);
    const tx = tgt.x;
    const ty = entryY.has(i) ? entryY.get(i) : Math.round(tgt.y + tgt.h / 2);

    // Where a column vertical sits: its allocated channel, spread about the
    // column centre and clamped so the leg still lands on the node's own face.
    const colVX = (run, box) => {
      const n = colVCount.get(run.key) || 1;
      const half = Math.max(0, box.w / 2 - DOCK_INSET);
      const off = (run.ch - (n - 1) / 2) * CH_SP;
      return Math.round(box.x + box.w / 2 + Math.max(-half, Math.min(half, off)));
    };
    const dockPt = () => {
      const run = p.dockRun || p.cv;
      const dx = run ? colVX(run, tgt) : Math.round(tgt.x + tgt.w / 2);
      return [dx, p.dock === 'top' ? tgt.y : tgt.y + tgt.h];
    };

    let pts;
    if (p.kind === 'dock') {
      // Out along the source's row, then into the target's column. One bend.
      const [dx, dy] = dockPt();
      pts = [[sx, sy], [dx, sy], [dx, dy]];
    } else if (p.kind === 'vexit') {
      // Down (or up) the source's own column, then in along the target's row.
      const ex = p.cv ? colVX(p.cv, src) : Math.round(src.x + src.w / 2);
      const ey = p.exitFace === 'bottom' ? src.y + src.h : src.y;
      pts = [[ex, ey], [ex, ty], [tx, ty]];
    } else if (p.kind === 'strip' && (p.dock || p.exitFace)) {
      // Ride the strip, entering it from under the source and/or leaving it up
      // into the target's own column. Each end that docks removes both a gutter
      // vertical and the stub that used to reach it.
      const hy = stripY(p.rl, p.side, p.h1.ch);
      const ex = p.exitFace
        ? (p.cv ? colVX(p.cv, src) : Math.round(src.x + src.w / 2))
        : gutterX(p.g1, p.v1.ch);
      const head = p.exitFace
        ? [[ex, p.exitFace === 'bottom' ? src.y + src.h : src.y]]
        : [[sx, sy], [ex, sy]];
      const gx2 = p.dock ? dockPt()[0] : gutterX(p.g2, p.v2.ch);
      const tail = p.dock ? [[gx2, dockPt()[1]]] : [[gx2, ty], [tx, ty]];
      pts = [...head, [ex, hy], [gx2, hy], ...tail];
    } else if (p.kind === 'straight' || (p.kind === 'elbow' && sy === ty)) {
      pts = [[sx, sy], [tx, ty]];
    } else if (p.kind === 'elbow') {
      const gx = gutterX(p.g1, p.v1.ch);
      pts = [[sx, sy], [gx, sy], [gx, ty], [tx, ty]];
    } else {
      const g1x = gutterX(p.g1, p.v1.ch);
      const g2x = gutterX(p.g2, p.v2.ch);
      const hy  = stripY(p.rl, p.side, p.h1.ch);
      pts = [[sx, sy], [g1x, sy], [g1x, hy], [g2x, hy], [g2x, ty], [tx, ty]];
    }

    for (let k = 1; k < pts.length; k++) allSegs.push([pts[k - 1], pts[k], i]);
    edgePts[i] = pts;
  }

  // Name each flow on its longest horizontal run — a routing channel, so the
  // label sits in reserved space. Labels are placed only now, once every line
  // exists, so a label can step off another flow's line as well as off shapes
  // and other labels. Without an explicit BPMNLabel bpmn-js drops every label at
  // the edge midpoint, and flows converging on one gateway land on each other.
  const segBox = (seg) => ({ x: Math.min(seg[0][0], seg[1][0]), y: Math.min(seg[0][1], seg[1][1]),
    w: Math.max(Math.abs(seg[1][0] - seg[0][0]), 1), h: Math.max(Math.abs(seg[1][1] - seg[0][1]), 1) });
  for (let i = 0; i < ir.flows.length; i++) {
    const pts = edgePts[i];
    if (!pts) continue;
    const f = plans[i].f;
    const flowId = 'flow_' + f.from + '_' + f.to + '_' + i;
    edgeLines.push('      <bpmndi:BPMNEdge id="' + flowId + '_di" bpmnElement="' + flowId + '">');
    for (const pt of pts) {
      edgeLines.push('        <di:waypoint x="' + pt[0] + '" y="' + pt[1] + '" />');
    }
    if (f.name) {
      let best = null;
      for (let k = 1; k < pts.length; k++) {
        if (pts[k][1] !== pts[k - 1][1]) continue;
        const len = Math.abs(pts[k][0] - pts[k - 1][0]);
        if (!best || len > best.len) best = { len, cx: (pts[k][0] + pts[k - 1][0]) / 2, cy: pts[k][1] };
      }
      if (!best) best = { cx: pts[0][0], cy: (pts[0][1] + pts[pts.length - 1][1]) / 2 };

      const lw = Math.min(150, Math.max(28, f.name.length * 6 + 8));
      const box = { x: Math.round(best.cx - lw / 2), y: Math.round(best.cy - 19), w: lw, h: 14 };
      const clashes = () =>
        labelBoxes.some(b => boxHit(box, b)) ||
        [...nodePos.values()].some(q => boxHit(box, q)) ||
        allSegs.some(seg => seg[2] !== i && boxHit(box, segBox(seg)));
      // Step off the channel until the slot is free; give up rather than drift
      // far from the edge it names.
      for (let guard = 0; guard < 10 && clashes(); guard++) box.y -= 16;
      labelBoxes.push(box);
      edgeLines.push('        <bpmndi:BPMNLabel>');
      edgeLines.push('          <dc:Bounds x="' + box.x + '" y="' + box.y +
                 '" width="' + box.w + '" height="' + box.h + '" />');
      edgeLines.push('        </bpmndi:BPMNLabel>');
    }
    edgeLines.push('      </bpmndi:BPMNEdge>');
  }

  // ── Node shapes, with labels on a side no line runs through ──────────────
  // Events and gateways carry their name outside the shape. Try the four sides
  // in reading order, skipping any face an edge attaches to, and take the first
  // box that touches no other shape, label or line. Falling back to "below" is
  // what bpmn-js would have done anyway.
  const faceOf = (pt, pos) => {
    if (Math.abs(pt[1] - pos.y) < 1) return 'top';
    if (Math.abs(pt[1] - (pos.y + pos.h)) < 1) return 'bottom';
    if (Math.abs(pt[0] - pos.x) < 1) return 'left';
    if (Math.abs(pt[0] - (pos.x + pos.w)) < 1) return 'right';
    return null;
  };
  const otherNodes = [...nodePos.entries()];
  for (const n of ir.nodes) {
    const pos = nodePos.get(n.id);
    if (!pos) continue;
    const isCompact = (n.type === 'startEvent' || n.type === 'endEvent' || GATEWAY_TYPES.has(n.type));
    lines.push('      <bpmndi:BPMNShape id="' + n.id + '_di" bpmnElement="' + n.id + '">');
    lines.push('        <dc:Bounds x="' + pos.x + '" y="' + pos.y +
               '" width="' + pos.w + '" height="' + pos.h + '" />');
    if (isCompact && n.name) {
      const attached = new Set();
      for (const seg of allSegs) for (const pt of [seg[0], seg[1]]) { const f = faceOf(pt, pos); if (f) attached.add(f); }
      const textW = n.name.length * 6 + 8;
      const lw = Math.min(90, Math.max(40, textW));
      const lh = 14 * Math.max(1, Math.ceil(textW / 90));
      const cx = pos.x + pos.w / 2, cy = pos.y + pos.h / 2;
      const candidates = {
        bottom: { x: cx - lw / 2, y: pos.y + pos.h + 4, w: lw, h: lh },
        top:    { x: cx - lw / 2, y: pos.y - lh - 4,   w: lw, h: lh },
        right:  { x: pos.x + pos.w + 6, y: cy - lh / 2, w: lw, h: lh },
        left:   { x: pos.x - lw - 6,    y: cy - lh / 2, w: lw, h: lh },
      };
      const order = ['bottom', 'top', 'right', 'left'];
      const free = order.filter(s => !attached.has(s)).concat(order.filter(s => attached.has(s)));
      const clear = (box) =>
        !otherNodes.some(([id, q]) => id !== n.id && boxesHit(box, q)) &&
        !labelBoxes.some(b => boxesHit(box, b)) &&
        !allSegs.some(seg => segHitsBox([seg[0], seg[1]], box));
      const side = free.find(s => clear(candidates[s])) || 'bottom';
      const box = candidates[side];
      box.x = Math.round(box.x); box.y = Math.round(box.y);
      labelBoxes.push(box);
      lines.push('        <bpmndi:BPMNLabel>');
      lines.push('          <dc:Bounds x="' + box.x + '" y="' + box.y + '" width="' + box.w + '" height="' + box.h + '" />');
      lines.push('        </bpmndi:BPMNLabel>');
    }
    lines.push('      </bpmndi:BPMNShape>');
  }
  for (const l of edgeLines) lines.push(l);

  lines.push('    </bpmndi:BPMNPlane>');
  lines.push('  </bpmndi:BPMNDiagram>');
  return { diSection: lines.join('\n'), problems: [] };
}

// Inject BPMNDI section + required namespace declarations into moddle-generated XML.
// moddle omits bpmndi/dc/di namespaces when no DI elements exist in the model tree.
function injectLaneDI(xml, diSection) {
  let result = xml;
  if (result.indexOf('xmlns:bpmndi=') === -1) {
    result = result.replace(
      /(<bpmn:definitions)(\s)/,
      '$1' +
      ' xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"' +
      ' xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"' +
      ' xmlns:di="http://www.omg.org/spec/DD/20100524/DI"' +
      '$2'
    );
  }
  return result.replace('</bpmn:definitions>', diSection + '\n</bpmn:definitions>');
}

// ── Layout audit ──────────────────────────────────────────────────────────────
// Reads the DI back out of the finished XML and measures what a reader would
// see: crossings, lines running over each other, lines through shapes, labels
// on top of things. Whether the crossing count is acceptable is decided by the
// Python side, which knows if the flow graph is planar.
function auditLayout(xml) {
  const attr = (attrs, name) => { const m = new RegExp(name + '="([^"]*)"').exec(attrs); return m ? m[1] : null; };
  const bounds = (block) => {
    const m = /<dc:Bounds\s+([^>]*)\/>/.exec(block);
    return m ? { x: +attr(m[1], 'x'), y: +attr(m[1], 'y'), w: +attr(m[1], 'width'), h: +attr(m[1], 'height') } : null;
  };
  const labelBounds = (block) => {
    const m = /<bpmndi:BPMNLabel>([\s\S]*?)<\/bpmndi:BPMNLabel>/.exec(block);
    return m ? bounds(m[1]) : null;
  };
  const ends = new Map(), names = new Map();
  for (const m of xml.matchAll(/<bpmn2?:sequenceFlow\b([^>]*)>/g)) {
    ends.set(attr(m[1], 'id'), [attr(m[1], 'sourceRef'), attr(m[1], 'targetRef')]);
  }
  for (const m of xml.matchAll(/<bpmn2?:\w+\b([^>]*\bid="[^"]+"[^>]*)>/g)) {
    const id = attr(m[1], 'id'), name = attr(m[1], 'name');
    if (id && name) names.set(id, name);
  }
  const shapes = [], edges = [];
  for (const m of xml.matchAll(/<bpmndi:BPMNShape\b([^>]*)>([\s\S]*?)<\/bpmndi:BPMNShape>/g)) {
    const id = attr(m[1], 'bpmnElement');
    const b = bounds(m[2].replace(/<bpmndi:BPMNLabel>[\s\S]*?<\/bpmndi:BPMNLabel>/, ''));
    if (!b) continue;
    shapes.push({ id, name: names.get(id) || id, ...b, container: /isHorizontal="true"/.test(m[1]), label: labelBounds(m[2]) });
  }
  for (const m of xml.matchAll(/<bpmndi:BPMNEdge\b([^>]*)>([\s\S]*?)<\/bpmndi:BPMNEdge>/g)) {
    const id = attr(m[1], 'bpmnElement');
    const pts = [...m[2].matchAll(/<di:waypoint\s+x="([\d.-]+)"\s+y="([\d.-]+)"/g)].map(w => [+w[1], +w[2]]);
    const [src, tgt] = ends.get(id) || [null, null];
    edges.push({ id, name: names.get(id) || id, pts, src, tgt, label: labelBounds(m[2]) });
  }
  const r = auditGeometry({ shapes, edges });
  const nm = (id) => names.get(id) || id;
  return {
    crossings: r.crossings, overlaps: r.overlaps, throughShape: r.throughShape, labelCollisions: r.labelCollisions,
    crossingPairs: r.crossingPairs.map(p => [nm(p.a), nm(p.b)]),
    throughPairs: r.throughPairs.map(p => [nm(p.edge), nm(p.shape)]),
  };
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  let ir;
  try {
    ir = JSON.parse(await readStdin());
  } catch (err) {
    process.stdout.write(JSON.stringify({
      ok: false, xml: '',
      problems: [{ kind: 'parse', message: `IR JSON parse error: ${err.message}` }],
    }));
    return;
  }

  // Guard: the IR must carry node/flow arrays before any pass touches them.
  // A malformed IR (e.g. LLM returned partial JSON, or omitted a key) would
  // otherwise crash normalizeGateways with "Cannot read properties of
  // undefined (reading 'map')". Report it as a structured problem so the
  // repair loop can ask the LLM to regenerate rather than dying fatally.
  const shapeProblems = [];
  if (!ir || typeof ir !== 'object') {
    shapeProblems.push({ kind: 'parse', message: 'IR is not an object' });
  } else {
    if (!Array.isArray(ir.nodes)) {
      shapeProblems.push({ kind: 'parse', message: 'IR is missing a "nodes" array' });
    }
    if (!Array.isArray(ir.flows)) {
      shapeProblems.push({ kind: 'parse', message: 'IR is missing a "flows" array' });
    }
  }
  if (shapeProblems.length) {
    process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: shapeProblems }));
    return;
  }

  // Pass 1 — normalise (deterministic; no LLM involvement)
  const normIR = normalizeGateways(ir);

  // Guard: normalisation must eliminate all non-gateway fan-in / fan-out.
  // If any remain it is a pipeline bug — surface it so the repair loop handles it.
  const structProblems = assertNoImplicitSplitOrJoin(normIR);
  if (structProblems.length) {
    process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: structProblems, normalizedIR: normIR }));
    return;
  }

  // Pass 2 — pairing failures are structural; stop before compiling bad IR
  const pairingProblems = assertGatewayPairing(normIR);
  if (pairingProblems.length) {
    process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: pairingProblems, normalizedIR: normIR }));
    return;
  }

  // Lane structural checks — must pass before compilation so the repair loop
  // can ask the LLM to fix missing or invalid lane assignments.
  if (normIR.lanes && normIR.lanes.length) {
    const laneProblems = assertLaneAssignment(normIR);
    if (laneProblems.length) {
      process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: laneProblems, normalizedIR: normIR }));
      return;
    }
  }

  // Pass 3 — compile to BPMN XML + add layout DI.
  // Every diagram goes through the same builder. A lane-less IR is laid out on
  // one hidden lane with no pool drawn; bpmn-auto-layout, which used to take
  // that case, produced 59 crossings on a 47-node map.
  let xml;
  try {
    xml = await compileIRtoBpmn(normIR);
    const hasLanes = !!(normIR.lanes && normIR.lanes.length);
    const gridIR = hasLanes ? normIR : {
      ...normIR,
      lanes: [{ id: '__lane', name: normIR.name || 'Process' }],
      nodes: normIR.nodes.map(n => ({ ...n, lane: '__lane' })),
    };
    // buildManualLaneDI also validates Y-bounds and returns problems on failure.
    const { diSection, problems: diProblems } = buildManualLaneDI(gridIR, { pool: hasLanes });
    if (diProblems.length) {
      process.stdout.write(JSON.stringify({ ok: false, xml: '', problems: diProblems, normalizedIR: normIR }));
      return;
    }
    xml = injectLaneDI(xml, diSection);
  } catch (err) {
    process.stdout.write(JSON.stringify({
      ok: false, xml: '',
      problems: [{ kind: 'compile', message: `Compile error: ${err.message}` }],
    }));
    return;
  }

  // Measure the drawing. These are reported, not fatal: the XML is valid and
  // executable either way. Crossings are judged on the Python side against the
  // graph's planarity, which decides whether zero or one is the floor.
  const layout = auditLayout(xml);
  const problems = [];
  if (layout.throughShape) problems.push({ kind: 'layout', rule: 'edge-through-shape', elementId: '',
    message: layout.throughShape + ' line(s) pass through a shape they do not connect: ' + JSON.stringify(layout.throughPairs.slice(0, 5)) });
  if (layout.overlaps) problems.push({ kind: 'layout', rule: 'collinear-overlap', elementId: '',
    message: layout.overlaps + ' pair(s) of lines run on top of each other.' });
  if (layout.labelCollisions) problems.push({ kind: 'layout', rule: 'label-collision', elementId: '',
    message: layout.labelCollisions + ' label(s) sit on a shape or a line.' });

  // Semantic validation is handled by the Python bpmn_validator layer after this step.
  // normalizedIR is returned so the repair loop can show the LLM the complete structure
  // (including compiler-inferred gateways) when asking for corrections.
  process.stdout.write(JSON.stringify({ ok: true, xml, problems, normalizedIR: normIR, layout }));
}

// Run as a program when invoked directly; importable (for tests) otherwise.
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main().catch(err => {
    process.stdout.write(JSON.stringify({
      ok: false, xml: '',
      problems: [{ kind: 'fatal', message: err.message }],
    }));
    process.exit(1);
  });
}

export { auditLayout, buildManualLaneDI, compileIRtoBpmn, normalizeGateways };
