name: Deploy CI/CD to BA site

on:
  workflow_dispatch:
  push: # tells github to run this on any push to the repository
    branches:
      - staging

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 90

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to BA site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BA_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.BA_KEY }}
          port: 22
          script: |
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            node -v
            cd /home/frappe/sandbox-bench/apps/one_bpmn
            git pull upstream staging
            cd /home/frappe/sandbox-bench
            rm -rf env/lib/python*/site-packages/one_bpmn-*.dist-info
            bench setup requirements one_bpmn
            cd /home/frappe/sandbox-bench/apps/one_bpmn/spiff
            yarn install
            export NODE_OPTIONS="--max-old-space-size=8192"
            yarn build
            cd /home/frappe/sandbox-bench
            bench --site business-analyst.one-fm.com migrate
            bench --site business-analyst.one-fm.com build --app one_bpmn
            bench --site business-analyst.one-fm.com clear-cache
            bench restart
